### ISSUE TITLE
Map Coverage.geographic during CSV import

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#102]
Given a CSV with a Coverage.geographic column:

 - [ ] importing this CSV creates objects with the values in the `location` attribute.

Depends on #101

**Comment by hardyoyo** [comment]
@no_reply suggests this as a good example to follow: https://github.com/UCLALibrary/californica/pull/209/files#diff-0adc64ccb160ec9574ef440a60ec7755

**Comment by hardyoyo** [comment]
And our CSV file is indispensable for finding appropriate sample values for new fields: https://ucla.app.box.com/file/310898959333
