### ISSUE TITLE
Refine predicate for `Description.longitude`

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#103]
In the current metadata spreadsheet, this is overloaded onto `dce:coverage`.

Either:

  - [ ] Determine an alternate (refined) predicate for longitude
or:
  - [ ] agree that the overloaded predicate is acceptable for this property.

https://docs.google.com/spreadsheets/d/1muoNt40y7nKPlthOr_CwuvvXdQLM2uYhEu55GXhASnU/edit#gid=0

**Comment by mark-dce** [comment]
superseded by #151
