### ISSUE TITLE
Determine vocabulary needs for `isPartOf`

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#105]
The current metadata spreadsheet points to using a controlled vocabulary for `isPartOf`.

- [ ] determine at least one controlled term for this attribute
- [ ] write tickets for an initial controlled vocabulary implementation.
or:
- [x] agree that this is a free text field

Connected to #71

**Comment by mark-dce** [comment]
@no-reply per discussion in #71, I think we just want to set this to a static value of "Los Angeles Times Photographic Archive. Department of Special Collections, Charles E. Young Research Library, UCLA."  For the scope of this project, I think we should is the extent of any controlled vocabulary requirements for "isPartOf"
