### ISSUE TITLE
A Work has a Publisher

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#106]
Add a `publisher` attribute for the `Work` class:

  - [x] A Work object can have a `publisher` field
  - [x] The predicate for it is `dc11:publisher`
  - [x] The label for it is "Publisher"
  - [ ] Ensure `publisher` has tests in place similar to other fields

**Comment by mark-dce** [comment]
@no-reply isn't this part of Hyrax::BasicMetadtata: https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb#L24

Can we close this ticket as being done?
