### ISSUE TITLE
Discuss Date handling needs

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#108]
Hyrax supports a range of dates, including system tracked dates.

 - [ ] Write up an initial overview of the different kinds of dates we will store on objects.
   - [ ] list whether each date is system tracked or user managed
   - [ ] list date format
   - [ ] ensure stakeholders can understand the various dates and their relationships.

**Comment by mark-dce** [comment]
For phase 1 we're planning to keep things simple by mapping `Date.creation` to `date_created` (which is provided by Hyrax::BasicMetadata) and `Date.normalized` to `normalized_date` see #152
