### ISSUE TITLE
Discuss Rights needs

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#109]
The current spreadsheet includes many fields mapped to `dc:rights`. We need to sketch an initial rights handling approach:

  - [x] Decide whether to use Hyrax's built-in RightsStatements.org vocabulary.
The answer is NO, do not use rightsstatements.org. I'm managing some political stuff here and the last thing I need to be seen as pre-empting (even in an iterative way) that conversation. 
  - [X] Decide whether to use Hyrax's built-in CC Licenses vocabulary.
    *After discussion, we have decided to replace the license vocabulary with licenses specific to UCLA*
  - [x] Choose unique predicates for various rights fields.
  - [ ] ~Produce a document describing the overall rights handling approach for the collection to share with stakeholders.~

**Comment by emcaulay** [comment]
Currently UCLA Library is debating whether to use RightsStatements.org. In lieu of that official decision, the Digital Library should not even provisionally adopt that approach. So for check box 1, the answer is no. Checking that off now.

**Comment by emcaulay** [comment]
I will take this action to answer checkbox 2:
- [ ] seek out documentation about Hyrax's built-in CC Licenses vocabulary

**Comment by emcaulay** [comment]
Don't know whether I should or not, but I'm labeling this Sprint 4.... maybe that's jumping the gun.

**Comment by hardyoyo** [comment]
This is a blocker for #97, a coding task, any chance there's been progress on this?

**Comment by mark-dce** [comment]
For the immediate term, we will update the license vocabulary with the terms needed to support the LADNN collection.  See #243
