### ISSUE TITLE
Setup default admin user

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#11]
## Acceptance
  - [x] With a fresh deploy, I can login as an admin user with a default username and password
    - [x] username and password are documented in the project wiki
  - [x] When logged in as this user, I can access the admin dashboard features:
    - [x] Review Submissions
    - [x] Manage Embargoes
    - [x] Manage Leases
    - [x] Settings

**Comment by bess** [comment]
Login and password added to wiki here: https://github.com/UCLALibrary/californica/wiki
