### ISSUE TITLE
Map repository name in CSV importer

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#121]
Given a CSV for the Los Angeles Daily News Negatives Collection

- [x] importing this CSV creates objects with a metadata field for "Repository" 
- [x] each object's metadata field for Repository has the value: "University of California, Los Angeles. Library. Department of Special Collections"

**Comment by val99erie** [comment]
@emcaulay Could you clarify:  Is the CSV column 'Name.repository', or is there another column called 'Repository' ?

**Comment by val99erie** [comment]
@emcaulay Never mind!  I see from reading the comments on story #70 that this should be `Name.repository`.  Thanks!
