### ISSUE TITLE
Update app name

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#13]
## Acceptance:

- [x] Select a (temporary) product name for the management application.

The following items reflect the name and UCLA's ownership:
  - [x] `application_name`
  - [x] `product_name`
  - [x] `institution_name` (title banner)

needs #14

**Comment by billha** [comment]
Confirmed this with @emcaulay. We will use "Samvera" as the temporary product name. This should result with the logo "UCLA Library" followed by "Samvera" in white in the top bar of the web site. The bar should have the same color blue as the logo.

#see 14

**Comment by hardyoyo** [comment]
copying over from a Slack thread, quoting @no-reply : https://github.com/UCLALibrary/samvera-mgmt/commit/649ee9a1b4512d960623ca1c0049e5c0ff95540b and https://github.com/UCLALibrary/samvera-mgmt/commit/cc64a421c6c0ba647ffd5cc289f33332bc2f47f8 might be helpful breadcrumbs

**Comment by hardyoyo** [comment]
PR #20 addresses both #13 and #14

**Comment by emcaulay** [comment]
I don't see the acceptance criteria checked off above, and I don't know how to verify them. So I feel uncertain about whether this is actually closed.

**Comment by emcaulay** [comment]
I cannot figure out how to move #20 back to review. So I moved this card (#13) which #20 appears stuck to.

**Comment by emcaulay** [comment]
Can someone document what the answers to @no-reply 's checkboxes are above?
E.g., I think ....
Institution Name and logo are "UCLA Library"
But I think we're talking about actual updates to Code inside the Samvera Management App. Not sure I know what I'm talking about though.
