### ISSUE TITLE
Map `Date.creation` in CSV importer

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#147]
Given a CSV with a `Date.creation` column:

 - [x] importing this CSV creates objects with the values in the `date_created` attribute.

**Comment by emcaulay** [comment]
I got to sit in with Val as she did this work earlier today -- very useful. @val99erie , is it appropriate to move this ticket over to the "in review" column?

**Comment by val99erie** [comment]
@emcaulay Usually I'd wait until the PR gets merged into master before moving the story to the 'review' column.  That way, if someone wants to do any testing (user acceptance testing or QA or just trying out the new code), they can deploy it to a testing environment and review the behavior.

**Comment by emcaulay** [comment]
okay ! thanks for guiding me through this process.

**Comment by val99erie** [comment]
@emcaulay We do have the ability to deploy branches out to the testing environments, and we might do that for large features or risky code, but for normal cases, it easiest to always just deploy master to the testing environments.  That way no one will be surprised if there is different code than they expected in the testing environment.

**Comment by emcaulay** [comment]
Okay -- thanks, I'm learning about this process.
