### ISSUE TITLE
Create items through the ActorStack process on CSV import

### ISSUE THREAD

**Issue by no-reply** [UCLALibrary/californica#161]
When ingesting CSV items, the items should run through Californica's default "Actor Stack". This stack handles a variety of import-time processes like adding system maintained created/modified dates, enqueuing derivative generation and file characterization, interpreting and applying permissions, etc...

Items created with the importer should be subject to the application defaults for these processes: 

**Acceptance:**

New items created through the CSV importer should: 
  - [ ] have thumbnails;
  - [ ] have FITS metadata on their files;
  - [ ] have an admin set

**Comment by mark-dce** [comment]
Depends on #188

**Comment by no-reply** [comment]
In working on this, I have realized the dependency is inverted. #188 depends on this, much more significantly than the other way around.
