### ISSUE TITLE
Ensure everyone on the Dev & Ops Teams can deploy the code

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#17]
## ACCEPTANCE
Each of the following folks can deploy
- [x] Stephen
- [x] Hardy
- [x] Kristian
- [x] Darrow
- [x] Kevin
- [x] Andrew
- [x] Bess
- [x] Tom
- [x] Mark B.

**Comment by emcaulay** [comment]
WHOOOHOOOOOO!
