### ISSUE TITLE
Map `Description.caption` in the CSV Importer

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#179]
Given a CSV with a `Description.caption` column:

 - [x] importing this CSV creates objects with the values in the `caption` attribute.

Depends on #178

**Comment by emcaulay** [comment]
Since I paired with @val99erie on a similar ticket on Friday, I felt really inspired to try to do it myself on this ticket. 

However, I have needed remedial help from @hardyoyo and @bess  on the environment setup.

**Comment by emcaulay** [comment]
I believe I have created a pull request that completes this task. https://github.com/UCLALibrary/californica/pull/190
