### ISSUE TITLE
extent appears on show view twice

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#199]
- [ ] The 'extent' field displays twice on the show view. It should only display once. See, e.g., http://cd-ucla.curationexperts.com/concern/works/vh53ww93p?locale=en and attached screen shot

**Comment by bess** [comment]
![extent_twice.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46ed8c8e268c97969bfeb640a11fbcd6395428792c07b7692ac7b62aec477f505b5747fd41510e11fcf98879a0bf3b768b5919f1c32f0e2a92624cf5f2d75dad0ba8228a4584b3bf8d4fc6e83e22e6828f4f2c53.png)

**Comment by val99erie** [comment]
The `extent` field appears twice in this file:
`app/views/hyrax/base/_attribute_rows.html.erb `
