### ISSUE TITLE
Error logging for CSV import

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#202]
The log file for the CSV ingest should tell us what succeeded and what failed:

In the log file:
- [x] I can tell how many objects were successfully imported
- [x] I can see what objects hit an error
- [x] I see what error was encountered so I can go track it down

**Comment by emcaulay** [comment]
I like these attributes of error logging, thank you.

**Comment by no-reply** [comment]
The first pass at this work looks pretty good overall, but has some complexity/side-effects that broke the build. I'm putting in some simplifying refactors.
