### ISSUE TITLE
[SPIKE] Evaluate Solr Synchronization options

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#205]
**ISSUE**
We need an initial recommendation for how to replicate information between two Solr instances (i.e. from the Solr supporting ingest and management of objects in californica *to* the Solr supporting public discovery in ursus).

There are multiple means to accomplish this including native Solr replication tools (https://lucene.apache.org/solr/guide/6_6/index-replication.html), a cron-scheduled native rails task, and many other options.

**ACCEPTANCE**
- [x]  Time box evaluation of at least three options
    - [x] Native Solr-replication
    - [x] Rails based task
    - [x] some other alternative
- [x] Recommend a solution or outline additional requirements that need to be address before making a selection.

Parent of https://github.com/UCLALibrary/ursus/issues/1
Depends on UCLALibrary/amalgamated-samvera#100

**Comment by mark-dce** [comment]
![experts 45](https://user-images.githubusercontent.com/3064318/45907586-23641e80-bdbe-11e8-99f3-2c8091ce272a.jpg)

**Comment by no-reply** [comment]
I owe some updates to this ticket.

**Comment by sgurnick** [comment]
Based on discussions I've had over the last few days with @hardyoyo @val99erie @little9 - I would like to put forth the following comments about our Solr architecture. 

We should be aware that whatever decision we make with Solr architecture for phase 1, should also be compatible with SolrCloud.

It is our (UCLA Library) intention, in a future project phase, to implement SolrCloud. With this in mind, we should be planning for an environment where all of our Blacklight and Samvera server environments are pointing to a common Solr ecosystem.

A common Solr ecosystem (e.g. SolrCloud) can include different indexes, if necessary, and is meant to be scaleable and provide for high availability and reliability. It is not efficient or advisable to create multiple common Solr ecosystems for each application - this defeats the purpose of SolrCloud. 

With this in mind, I submit to the team that our investigations for Solr index usage between our public facing and staff facing environments should lay the groundwork for SolrCloud.

Options that allow us to do this are:

1. Solr Replication between Californica and Ursus
    - The Solr master node would be connected to Californica and would be read-write
    - The Solr slave node would be connected to Ursus and would be read-only
2. Single Solr environment shared by Californica and Ursus
    - The single solr server (or scaled-out master/slave environment) would be shared by both Californica and Ursus.

Our ability to select an option is contingent upon the use-cases for Solr between Ursus and Californica. Therefore, I also suggest that we proceed with UCLALibrary/amalgamated-samvera#100 so we can gather as much information as possible before making a decision.

**Comment by little9** [comment]
Here is the doc that DCE put together outlining the pros and cons of various scenarios as part of this research spike: 

https://docs.google.com/document/d/1S-9Brc0U-2cRa6UREvAhFPD2_DTxnhx1bnpnVKv2P5s/edit?usp=sharing

**Comment by bess** [comment]
Looks like the recommendation is Native Solr-replication for phase 1, right?

**Comment by val99erie** [comment]
Yes, management has expressed a strong preference for a 2-solr solution in phase 1, and devops have expressed concerns about having enough time to set up SolrCloud in time for the end of phase 1.

So it looks like we should proceed with 2 solrs in a master-replica configuration with californica pointing to master and ursus pointing to a replica.

In future phases, if we start to approach the edge of acceptable performance, and if solr is the bottleneck (which is unlikely), then we can either switch to SolrCloud or add more replicas.
