### ISSUE TITLE
Add terms to the californica EDIT view

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#207]
**STORY**
As a librarian / archivist / metadata professional, I would like to bet able to edit all of the descriptive metadata associated with an object, so that I can ensure it's correctness.

**ACCEPTANCE**
Ensure each of the following fields appears on a single item edit page:
 - [x] Title
 - [x] Subject
 - [x] Type of Resource
 - [x] Copyright Status
 - [x] Name (subject)
 - [x] Location
 - [x] Repository
 - [x] Publisher
 - [x] Rights (country of origin)
 - [x] Rights Holder
 - [x] Date
 - [x] Local Identifier
 - [x] Title
 - [x] Date Created
 - [x] Extent
 - [x] Medium
 - [x] Dimensions
 - [x] Description
 - [x] Funding Note
 - [x] Longitude
 - [x] Latitude
 - [x] Caption
 - [x] Language

reference (CSV Mappings)[https://docs.google.com/spreadsheets/d/1muoNt40y7nKPlthOr_CwuvvXdQLM2uYhEu55GXhASnU/edit#gid=875035976]

**Comment by val99erie** [comment]
@mark-dce Is there a requirement that a user must be an admin to edit a record?  Or is that handled in a different story?

**Comment by mark-dce** [comment]
@val99erie yes, a user must be an admin to reach the edit form.   This requirement is already in place to the best of my knowledge.

**Comment by val99erie** [comment]
@mark-dce In my dev env, I am able to create and edit records as a non-admin user.  If having admin role is a requirement for create/edit, could you write a story for that?

**Comment by mark-dce** [comment]
@val99erie - hmmm, that's not the behavior I'm seeing in production.  For now in any case, the scope of this story is just to ensure that *all the fields* are editable, not just some of them, by whoever can get to the edit form.

And yes, we can definitely write authorization stories as needed at a later point.
