### ISSUE TITLE
Investigate native solr replication

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#215]
- [x] Is it still supported?
- [x] How much work would it be to set up?

Child of #205

**Comment by bess** [comment]
@sgurnick Does this match your understanding? Do you have other info indicating that this option is not a viable choice?

**Comment by sgurnick** [comment]
The official Solr 7.4 documentation for with respect to Index Replication is available here: https://lucene.apache.org/solr/guide/7_4/index-replication.html

Something for us to be aware of is the documentation categorizes this as a "legacy" configuration. I assume they are trying to get users away from master/slave replication and on to the SolrCloud set-up. 

As far as I'm aware, native solr master/slave replication is still functional. I have not come across any documentation that explicitly says to avoid it. 

Depending on what we are trying to achieve this could be an option for us to consider. We'll just want to keep in mind we are using a legacy (potentially deprecated) feature.
