### ISSUE TITLE
Investigate solr cloud

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#216]
- [x] Would this solve our issues for Californica / Ursus communication?
- [x] How much work would it be to set up?

Child of #205

**Comment by bess** [comment]
Docs here: https://lucene.apache.org/solr/guide/7_4/solrcloud.html

It seems like this will ultimately be what UCLA wants -- it's much more scalable and highly available. However:

1) It it not necessary to deliver our Phase 1 goals
2) It does not in and of itself solve the problem at hand, synchronization between californica and ursus

It seems like it will be a significant effort to set this up as a production service, and it will need to be done by the systems group, not by the application development team.

@sgurnick, do you have anything to add?

**Comment by sgurnick** [comment]
@bess this matches my understanding as well. Nothing further to add.
