### ISSUE TITLE
document the use cases for all Californica and Ursus dev and devops environments

### ISSUE THREAD

**Issue by hardyoyo** [UCLALibrary/californica#239]
There are at least three different developer and devops environments available to facilitate work on and related to Californica and Ursus. We should document the use cases for each environment, to avoid confusion and make clear why each environment exists.
### ACCEPTANCE

- [x] document use cases for the Native dev environment
- [x] document use cases for the Packer-built dev VM
- [x] document use cases for Vagrant-Embark

**Comment by sgurnick** [comment]
Wiki page completed: https://github.com/UCLALibrary/amalgamated-samvera/wiki
