### ISSUE TITLE
Configure sidekiq so "failures" are viewable from /sidekiq

### ISSUE THREAD

**Issue by ksclarke** [UCLALibrary/californica#241]
@emcaulay would like to see "failures" on the Sidekiq dashboard. Right now "Retries" show, but there are fewer retries than failures.

**Comment by ksclarke** [comment]
The gem sidekiq-failures looks like it will do what we need, but I think there is something missing in our localhost deploy config because changes to the Gemfile aren't deployed to the localhost location for the developer's box.

**Comment by hardyoyo** [comment]
Confirmed this is working as expected on Californica-test (see comments on #97) .
