### ISSUE TITLE
Update license vocabulary

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#243]
**STORY**
As a UCLA stakeholder, I would only like to see UCLA approved licensing statements in the dropdown for "Rights Statement"

**ACCEPTANCE**
- [x] Delete the default entries provided by Hyrax
- [x] Add the term "copyrighted" to the [Rights Statement](https://github.com/UCLALibrary/californica/blob/master/config/authorities/rights_statements.yml) vocabulary with the id http://rightsstatements.org/vocab/InC/1.0/

**Comment by hardyoyo** [comment]
![243-screenshot-2018-10-05 16-59-53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56f4740a96b3bf0e00763e33/125516c66e82c728ace21e0d46bac0c96e9180bb8aecb150ac52e4d97b16762b6455f36620d0a379e90f2e58425a4dbe5d4a1f06a3a3dc78e2a436628f0e08b8856c5b7ccf6c11a5e9d71fbf00e826824883b7b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb50f14ce74456a0113264f43b.png)
