### ISSUE TITLE
Mgmt: Metadata in search results

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#264]
The following fields should appear in the Californica search results (and any others should be removed):

- [x] Title
- [x] Description
- [x] Normalized Date
- [x] Resource Type

**Comment by hardyoyo** [comment]
what does "normalized date" meaan?

**Comment by emcaulay** [comment]
normalized.date is ISO 8601 representation of date. It’s used for machine processing but considered not human-friendly. E.g., iso8601: 1937/1941 is often written 1937-1941 or Between 1937 and 1941.
