### ISSUE TITLE
Mgmt: Edit form label for Normalized Date

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#269]
- [x] The label for the Normalized Date field in the edit form should be labeled as "Normalized Date"
- [x] This has been tested in californica-stage

See attached screen shot for what it looks like right now

**Comment by bess** [comment]
![normalized_date_label.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46e69b882e838fa095ecbb7ca05ce491164a26712c08e1673295f127b54778154d555ca9135b0a10fdfd8122f7b63521df5c0bec836b5673c03c14bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8c46381a031d89fa5a31a98b06.png)

**Comment by ksclarke** [comment]
![selection_005](https://user-images.githubusercontent.com/106238/47187988-2c380980-d304-11e8-9edb-cb0481325263.png)

**Comment by ksclarke** [comment]
Failed tests so more to do. Unfortunately, it's at the end of my day so will have to pick it up later.

    1) Edit an existing work logged in as an admin user successfully edits the work
      Failure/Error: expect(find_field('Date').value).to eq 'Old Normalized Date'
      Capybara::Ambiguous:
        Ambiguous match, found 2 elements matching visible field "Date" that is not disabled
        # ./spec/features/edit_work_spec.rb:66:in `block (3 levels) in <top (required)>'

**Comment by ksclarke** [comment]
Have committed what I think is a fix, but GitHub seems to be having issues at the moment. If I refresh the PR page sometimes the new commits show up and sometimes they don't, and no Travis build has been triggered for the new commits. Will monitor and check that Travis job has been kicked off once GitHub stabilizes again.
