### ISSUE TITLE
Change label "Subject" to "Subjects" on item view

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#272]
As a user, I think it is strange to see a bunch of subjects with the field label "subject". The plural would be more appropriate. 

Acceptance Criteria
- [x] On Californica when looking at the item view each record uses the label "Subjects" instead of "Subject"

**Comment by andrewbenedictwallace** [comment]
Briefly looked at this one – but changing "Subject" to "Subjects" in config/locales/hyrax.en.yaml doesn't seem to do it...

**Comment by mark-dce** [comment]
Rails provides a very nice pluralization capability.  The more elegant solution would be to pluralize when appropriate:

```
Subject:  unique

Subjects: this
         that
         the other
```
