### ISSUE TITLE
Mgmt: Add Photographer to Californica

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#279]
Add a photographer attribute for the Work class:

- [x]  A Work object can have a photographer field
- [x]  The predicate for it is http://bibfra.me/vocab/relation/photographer/
- [x] The label for it is "Photographer"
- [x] It appears on the item's show page in californica

Given a CSV with a name.photographer column:

- [x] importing this CSV creates objects with the values in the photographer attribute.

if desired, see the metadata mappings spreadsheet here: https://docs.google.com/spreadsheets/d/1muoNt40y7nKPlthOr_CwuvvXdQLM2uYhEu55GXhASnU/edit?usp=sharing

**Comment by mark-dce** [comment]
@emcaulay & @metaclaudiah the bibfra.me photographer should have an [Agent](http://bibfra.me/vocab/lite/Agent/) that it points to.  We probably want something that just expects a string right now - would it be ok to use http://id.loc.gov/vocabulary/relators/pht.html instead.

**Comment by bess** [comment]
I'm going to use  http://id.loc.gov/vocabulary/relators/pht.html for now. We can switch out the predicate easily later if we want.
