### ISSUE TITLE
Correct copyright metadata values

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#284]
The correct value is in the CSV. UCLA has not yet adopted rightsstatements.org so that metadata approach is not allowed at this time. 

Acceptance Criteria 

- [x] The value in the metadata for all items is the string value "copyrighted"
- [x] The metadata does NOT include a rightsstatement.org URI.
- [x] Change the value stored for `rights_statement` to `"http://vocabs.library.ucla.edu/rights/copyrighted"`

**Comment by bess** [comment]
@emcaulay Please see Line 9 of the metadata spreadsheet (https://docs.google.com/spreadsheets/d/1muoNt40y7nKPlthOr_CwuvvXdQLM2uYhEu55GXhASnU/edit#gid=875035976) and let's fill in the details.

**Comment by mark-dce** [comment]
Let's just change the URI in the rights vocabulary https://github.com/UCLALibrary/californica/blob/bf06193b884b8686f19aa1deef2f25c4e1bc8a24/config/authorities/rights_statements.yml#L2

Let's use "http://vocabs.library.ucla.edu/rights/InC/1.0/"
