### ISSUE TITLE
Mgmt: Remove "edit" button

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#285]
The scope of the project at the moment does not include the functionality of being able to edit items in Californica. Currently UCLA is not using the standard rightsstatements.org metadata schema for rights, so the Californica edit feature will not work. Rather than work on correcting the UI for edit, we are electing to remove the Edit button at this stage. 

**Acceptance Criteria**

 - [ ] No edit button visible on Californica UI

**Comment by mark-dce** [comment]
@emcaulay I think it's a mistake to remove this functionality.  We've done this in past projects and it becomes difficult to re-enable once too many additional changes to the metadata and object models occur that haven't been accounted for in the editing process.

**Comment by mark-dce** [comment]
Upon discussion, we've decided that we would like to keep edit functionality tracking changes to the object model as they occur rather than trying to catch up at some later time.
