### ISSUE TITLE
New CSV to reflect update DLCS metadata

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#295]
As a product sponsor, I want to make sure we are using the most accurate up to date metadata.

Depends on #110

**Comment by kjallen** [comment]
@emcaulay could you clarify what in #110 this ticket requires?

**Comment by emcaulay** [comment]
Claudia needed to do some work and now she has done it

**Comment by emcaulay** [comment]
All should know that the new CSV is online here: https://ucla.box.com/s/gzcf8kiwm47vmthptm95r9r6b4j4romq.

I am moving this to "For Release", and I will mention it at standup today. The date on the file is 10/26/18. Can anyone confirm whether we have used that CSV in any load recently?
