### ISSUE TITLE
Mgmt: Each description on its own line

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#296]

**Comment by emcaulay** [comment]
@sshaferUCLA  and @metaclaudiah are both needed, maybe? Can you both look? and then let me know whether you want to do it this sprint?

**Comment by bess** [comment]
![description_needs_own_line.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46ec918920908ab99be0b04d9b53f5912d55187c3e0a9c27798be66af3006b1300051bff054a5556f9ab8a7ef2b73878830d0be480385f74c76f17a5bf841eba13a632c91edbe2e3d7158abd7f37ed998e48341f001c89fa5532a19143c15df459ac.png)

**Comment by bess** [comment]
Closing and re-creating in ursus.
