### ISSUE TITLE
Public: Image Level Links

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/californica#308]
cf. wireframe UCLALibrary/ursus#71 (comment)

### Initial release 
Four record level images as examples. 

Eventually it has thumbnails of many item level exemplars. [See Stanford example](https://parker.stanford.edu/parker/)

### Titles
+ Swan float in the Tournament of Roses Parade, Pasadena, 1938 = https://ursus-stage.library.ucla.edu/catalog/th83kz455

+ Carlos Chávez, portrait

+ Side view of “The Tombstone”, a slab of the St. Francis Dam visible after its disastrous 1928 collapse.

+ Corridor filled with men and women tabulating ballots for California primary election in Los Angeles, Calif., 1954

---

### Subject browse (in white boxes)

1. Events = https://ursus-stage.library.ucla.edu/catalog?f%5Bsubject_sim%5D%5B%5D=FEvents

1. People = https://ursus-stage.library.ucla.edu/catalog?f%5Bsubject_sim%5D%5B%5D=People

1. Lifestyle = https://ursus-stage.library.ucla.edu/catalog?f%5Bsubject_sim%5D%5B%5D=Lifestyle

1. Government = https://ursus-stage.library.ucla.edu/catalog?f%5Bsubject_sim%5D%5B%5D=Government&search_field=all_fields

1. Disaster = https://ursus-stage.library.ucla.edu/catalog?f%5Bsubject_sim%5D%5B%5D=Disaster&search_field=all_fields

**Comment by bess** [comment]
Closing as duplicate.
