### ISSUE TITLE
Management: Enable serving compressed assets to speed page load time

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#320]
**STORY**
As a systems owner, I'd like to configure apache to serve the gzipped version of assets that are created during deployment of **CALIFORNICA**, so that end users get faster page loads.

**DETAILS**
For an overview, see the [Asset Pipeline Rails Guide](https://guides.rubyonrails.org/asset_pipeline.html), especially the gzip section of [Custoimizing the Pipeline](https://guides.rubyonrails.org/asset_pipeline.html#customizing-the-pipeline)

Additional info specific to Apache configuration can be found here:  
* https://coderwall.com/p/sx-8xa/serving-pre-compressed-assets-through-apache
* https://stackoverflow.com/questions/7509501/how-to-configure-mod-deflate-to-serve-gzipped-assets-prepared-with-assetsprecom/7510773#7510773

**ACCEPTANCE**
- [ ] gzipped versions of assets are created during deployment
- [ ] The Apache server for **Californica** is configured to serve the compressed versions of assets
  - [x] VM environment (embark)
  - [x] development environment
  - [x] test environment
  - [x] staging environment
  - [ ] production environment

Depends on https://github.com/UCLALibrary/ursus/issues/116

**Comment by hardyoyo** [comment]
here is the Apache config file which will need to have the mod_deflate config lines added:
https://github.com/UCLALibrary/uclalib_role_samvera_capdeploy/blob/master/templates/apache_vhost.j2

**Comment by hardyoyo** [comment]
pull request: https://github.com/UCLALibrary/uclalib_role_samvera_capdeploy/pull/32
