### ISSUE TITLE
Management: handle sass gem deprecation

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#321]
**ISSUE**
The `sass` gem currently used by the application will go end-of-life on 26 March 2019.

**DETAILS**
A thorough upgrade guide for upgrading to the `sash-rails` gem can be found here; http://sass.logdown.com/posts/7081811

**ACCEPTANCE**
- [ ] **CALIFORNICA** no longer depends on the `sass` gem (i.e. it no longer show up in `Gemfile.lock`)

**Comment by little9** [comment]
I did UCLALibrary/ursus#118 first. That can be copied for this ticket.
