### ISSUE TITLE
Management: Change "Named Subject" field to "Names"

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#322]
Acceptance Criteria:
- In **CALIFORNICA** The named_subject field is _labelled_ "Names" in:
  - [ ] Facet sidebar
  - [ ] Single-item display

See: https://github.com/UCLALibrary/ursus/pull/117

**Comment by mark-dce** [comment]
@metaclaudiah & @emcaulay - putting a note here to ask Claudia to review this ticket and:  

Option A) Leave the acceptance as-is if she's in agreement with this change to californica
OR
Option B) Adjust the acceptance criteria as needed
OR
Option C) Close the ticket with a "wont fix" label if she doesn't feel this is an appropriate change

**Comment by metaclaudiah** [comment]
@hardyoyo I am in agreement with the acceptance as it stands. (Mark's Option A above).

**Comment by hardyoyo** [comment]
![image](https://user-images.githubusercontent.com/611569/48288833-0699ae00-e433-11e8-8109-1aab40a90f3c.png)
on californica-test, closing this
