### ISSUE TITLE
Change the application name in the Californica banner

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#324]
**ACCETPANCE**
- [ ] Display the name "Californica" instead of "Samvera" in the banner

<img width="536" alt="californica-324" src="https://user-images.githubusercontent.com/3064318/48146568-e4f5c680-e27a-11e8-9e20-81c6ecfc3327.png">

**Comment by hardyoyo** [comment]
hints: https://github.com/UCLALibrary/californica/pull/20
