### ISSUE TITLE
Change the Californica header and footer color

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#325]
**STORY**
As a library user, I want a clear visual signal to help me know when I'm working with the management application vs. with the discovery application.

**ACCETPANCE**
- [ ] Change the background color on the header and footer to an orange (matching the poppy in the readme) or yellow (matching ucla branding) color

<img width="536" alt="californica-325" src="https://user-images.githubusercontent.com/3064318/48146999-ea9fdc00-e27b-11e8-8d6a-a633dc41458e.png">

**Comment by hardyoyo** [comment]
hints: https://github.com/UCLALibrary/californica/pull/20
