### ISSUE TITLE
Use UCLA Identifiers

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/californica#336]
Currently, californica is creating its own unique identifiers for items, which are used in URL in both californica and ursus. Our existing "ark" identifier is being ingested and preserved as the "Identifier" field, but californica and ursus do not actually treat is as an identifier or use it in URLs.

Dangers of the current approach:
- Potential for duplication of records w/ same ark.
- Confusion w/ users, proliferation of identifiers (we already have this "local identifier" thing, which I assume has its own history...)
- Breaking urls when we re-ingest and new identifiers are assigned.

Acceptance criteria:
- [ ] ~On ingest, californica uses the existing "Identifier" field (the ark) as the primary identifier.~
- [ ] ARKs are used for all single-item page URLs in californica and ursus, and in all inter-service communication.

**Comment by jendiamond** [comment]
- [ ] Enforce that all Work records have an ARK and that ARKs are unique
Currently the identifier is an optional field, but that won't work if we require ARKs in URLs
- [ ] Make the identifier required

**Comment by jendiamond** [comment]
1. Update the form
2. Write a validation importer
3.Model validation

**Comment by jendiamond** [comment]
[Uploading IMG_20190228_153034628.jpg...]

**Comment by mark-dce** [comment]
I'm blocking this for now so that we can do a wholistic review of all ARK / id related tickets.

**Comment by mark-dce** [comment]
After discussion, we've decided not to change the default behavior Fedora uses to generate its internal IDs, instead we're going to add a separate uniquely valued property for the `ark`

See: **Add an "ARK" property to the UCLA data model** #456
