### ISSUE TITLE
ingest log should report the number of records that were actually created

### ISSUE THREAD

**Issue by hardyoyo** [UCLALibrary/californica#339]
Upgrade darlingtonia to 3.x ￼…
This gives us:
* improved logging, including summary success/failure at
the end of each import
* the ability to attach works to collections at ingest
time
* the ability to track imports by batch number, which will be
increasingly important as we scale the number of concurrent imports

Currently the ingest.log shows how many records were processed, and how many were expected, which is helpful... however, we also need to know how many records were actually created.

**Comment by hardyoyo** [comment]
breadcrumbs:
https://github.com/curationexperts/darlingtonia/blob/master/lib/darlingtonia/record_importer.rb#L42-L48 is where I'd add an increment to keep track of how many records are actually created

There are two options: we can re-work the Darlingtonia gem, make a PR against it and ask DCE to cut a new release. OR we can "monkey patch" that method.

**Comment by emcaulay** [comment]
@jendiamond , you've assigned yourself to this ticket. Is it in progress?

**Comment by mark-dce** [comment]
FYI - DCE is currently working on the necessary changes in Darlingtonia

**Comment by bess** [comment]
This has been fixed in Darlingtonia and we should be able to take advantage of the fix by upgrading our gem version. I am trying that now.

**Comment by bess** [comment]
The output now looks like this:
```
event: finish_import, batch_id: , successful_record_count: 19, failed_record_count: 0
```

We aren't using batch ids yet, but when we want to scale up to many concurrent imports these are going to become very important.

**Comment by emcaulay** [comment]
By the way, this is so cool!
