### ISSUE TITLE
ingest process should not import the collection record

### ISSUE THREAD

**Issue by hardyoyo** [UCLALibrary/californica#340]
The CSV contains a collection record, which the ingest process dutifully ingests and produces a record which looks like the screenshot below. It shouldn't ingest this record, as it's not an item in the collection.

**Comment by hardyoyo** [comment]
![image](https://user-images.githubusercontent.com/611569/48725108-c1bf0580-ebf0-11e8-82d2-9b4ebe8055bc.png)

**Comment by bess** [comment]
Superseded by https://github.com/UCLALibrary/californica/issues/436
