### ISSUE TITLE
revise the capistrano deploy for californica to fail if an ingest is in process

### ISSUE THREAD

**Issue by hardyoyo** [UCLALibrary/californica#343]
Based on observations during an ingest on the californica-test server, where an ongoing ingest process failed due to a Jenkins deploy process based on the CD workflow (i.e. a pull request was merged to californica's master branch on github), the capistrano deploy task needs to fail if an ongoing ingest task is detected. This easily-recovered-from error (a failed deploy) is preferable to the more difficult to recover ingest process failure.

## ACCEPTANCE
- [x] the capistrano deploy fails if an ingest task is detected
- [x] the capistrano deploy works correctly under normal circumstances

**Comment by hardyoyo** [comment]
breadcrumbs:
https://capistranorb.com/documentation/getting-started/before-after/
https://capistranorb.com/documentation/advanced-features/ssh-kit/

**Comment by sgurnick** [comment]
I modified the ansible role that executes code deployments to check whether a `rake` task is running before proceeding.

If a `rake` take is running - the deploy process is stopped and marked as failed in jenkins. 

It's possible we may want to move this `rake` task check into the cap deploy process.
