### ISSUE TITLE
Revise rights metadata for all LADNN to use Creative Commons

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#349]
As the AUL (and Samvera Governing Board member) responsible for authorizing all rights activities in the UCLA Library, I wonder why the Samvera version of the Los Angeles Daily News Negatives collection does not use the Creative Commons license that I approved for this collection many years ago. Please correct this oversight. 

Approval Criteria:
- [ ] a CC BY 4.0 License is visible for every item. Replicating what is displayed now: http://digital2.library.ucla.edu/viewItem.do?ark=21198/zz002803cj

Blocked by https://github.com/UCLALibrary/amalgamated-samvera/issues/219

**Comment by mark-dce** [comment]
This is already in the code  
https://github.com/UCLALibrary/californica/blob/master/config/authorities/licenses.yml#L23

I think it's not in the source LADNN metadata, so it's not being imported???

**Comment by mark-dce** [comment]
* Update source metadata to include a cc-by-4.0 license for each record - 2pts.
* Update the importer to read the license field - 1pts.
* Ensure californica displays the correct license - 1pts.
* Ensure license is displayed in ursus - 1pts.

**Comment by emcaulay** [comment]
Can someone looks at this ticket and affirm what work remains to be done on this ticket?

**Comment by emcaulay** [comment]
![amalgamated_samvera_349.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b4154ac031c8c0012e97553/125516c66e82c728ace21e0d46e9999b2f8582a48efdba479b4ef1993f4335721657f77232c9a138ad4d71040c1b5ca6535d0d47a9ad882faebf6d70830d5eedd16c0d72cf3a17adbd9003ad43eb7edf10d8eff6df0ed2e22f24ef818e4a3a19051e88f85935a39f42da15.png)
This work was completed.
