### ISSUE TITLE
Running test_server twice breaks tests

### ISSUE THREAD

**Issue by ksclarke** [UCLALibrary/californica#35]
Not super high priority, because I can run the test_server once per VM session, but documenting for further investigation.

To repeat, on a clean checkout (in VM or on native):
1) (in 1st terminal): `bundle exec rake hydra:test_server`
2) (in 2nd terminal): `bundle exec rake spec` # tests succeed
3) (in 2nd terminal): `bundle exec rake spec` # tests succeed
4) (in 1st terminal): [Ctrl-C to stop hydra:test_server]
5) (in 1st terminal): `bundle exec rake hydra:test_server`
6) (in 2nd terminal): `bundle exec rake spec` # tests fail

My expectation is that the last `rake spec` would not have failed tests.

**Comment by andrewbenedictwallace** [comment]
Confirmed on a different VM. Failure message complains about missing "Add Work" button.

**Comment by ksclarke** [comment]
This looks like a fix: https://github.com/UCLALibrary/californica/pull/38

Testing it tomorrow.

**Comment by ksclarke** [comment]
Confirmed, PR fixes the problem.
