### ISSUE TITLE
ARK is available to blacklight as single-value field

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/californica#358]
Our existing ARK identifiers are currently being imported as a multi-valued field. In order to use it in e.g. URLs, it should instead be imported as a single-value field.

Q: Do any items have multiple ARKs? If so, perhaps use both "identifiers" and "primary identifier"???

Criteria:
- [ ] ARKs are available as a _single-valued_ field for blacklight

child of #336

**Comment by jendiamond** [comment]
+ change to the importer
+ write a rake task to get what’s already in there

**Comment by mark-dce** [comment]
@jendiamond - why don't you try searching the existing ID field for the first value beginning with "ark:" and then modify the `to_solr` method on the `Work` class to add that value to a field named something like `citation_id_ssi`  (_ssi = stored, searchable, indexed - no m means not multiple)

Here's two examples of modifying the to_solr method:  
https://github.com/ucsblibrary/alexandria/blob/master/app/models/concerns/local_authority_base.rb#L26-L31  (this is newer and probably better syntax than below)
https://github.com/ucsblibrary/alexandria/blob/master/app/models/concerns/local_authority_base.rb#L26-L31 (uncommenting the code here would do a similar thing)

@little9 & @val99erie - tagging the two of you to add your two cents on how to implement this - we want a single valued field with the ark in it to use for the primary blacklight.

**Comment by mark-dce** [comment]
@jendiamond - what @val99erie said 👍 - mine is probably the really old way of doing this which is why I had trouble finding good examples.

Val has basically already started this in this commit https://github.com/UCLALibrary/californica/commit/f8e2703736212221d683d7a1e0679531603d653f

**Comment by val99erie** [comment]
@jendiamond  To reindex your existing `Work` records in your production environment, here is a rake task that you can use:
`https://github.com/MPLSFedResearch/cypripedium/blob/master/lib/tasks/reindex.rake`

**Comment by jendiamond** [comment]
#### actual URL:
https://ursus-test.library.ucla.edu/catalog/ark://13030/hb038nb0bm

#### escaped URL:
https://ursus-test.library.ucla.edu/catalog/ark\:\/\/13030\/hb038nb0bm

https://ursus-test.library.ucla.edu/catalog/13030-hb038nb0bm


https://digital.library.unt.edu/ark:/67531/metadc1213294/

**Comment by jendiamond** [comment]
a.each { |w| w.identifier = ["ark:/" + w.identifier.first]; w.save }
