### ISSUE TITLE
Trial Ingest Will Connell Collection into Californica Dev

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#359]
As a greedy product owner, I am eager to see a second collection in Californica and Ursus to test the work we've done so far and see how the work done so far fits with a new collection.

Metadata is available here: https://ucla.box.com/s/m10c18njhkrchwpxt1tm69h0ejskgg2v

Lisa and Stephen will need to coordinate copying the master images to a mount point.
Copy masters from Netapp masters location to mount point for inngest into Samvera: \\svm-netapp-dlib.in.library.ucla.edu\Masters\\dlmasters\connell\image

## Acceptance Criteria
- [x] A full attempt to load all 503 objects from the Will Connell collection into Californica-dev took place
- [x] Notes of findings, errors, lessons-learned are made on this ticket

**Comment by sgurnick** [comment]
I placed the `images` directory of the **connell** collection in the `/opt/data`shared mount point . This is now on each of our server environments. 

If you someone can point me to the metadata CSV file I can move it there as well.

**Comment by mark-dce** [comment]
@sgurnick - can you access the metadata file from box linked in the main ticket description?

**Comment by sgurnick** [comment]
Connell collection metadata file is at: `/opt/data/dlcs_connell_20181204.csv`

Connell collection images are at: `/op/data/connell/images`

**Comment by bess** [comment]
See https://californica-dev.library.ucla.edu/

**Comment by bess** [comment]
As of Thursday Dec 13 the import is failing because of a "ArgumentError: invalid date" error. Stack trace here: https://rollbar.com/uclalibrary/CalifornicaDev/items/7/
Working on resolving that now.

**Comment by emcaulay** [comment]
Enjoying watchng this! Very excited!

**Comment by bess** [comment]
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/232
Connected to https://github.com/UCLALibrary/amalgamated-samvera/issues/231
