### ISSUE TITLE
Document pre-ingest preparation workflow for loading a collection into Samvera

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#361]
As a digital library team member or as a Samvera Project team member, I want to have a document that guides me through the steps of ingesting a new collection into Samvera. 

Acceptance Criteria
- [x] A draft document accessible on UCLA Confluence exists that guides someone through the current state process of ingesting a new collection
- [x] Selected team members have reviewed the document
  - [x] @mark-dce 
  - [x] @joshuago78 
  - [x] @croft103 
  - [x] @jendiamond

**Comment by emcaulay** [comment]
I will come back to this on Monday, but I'm certain we will not work on this in sprint 14. I need to schedule a meeting with Bess, and I think that might be for March 8 at the earliest.

**Comment by bess** [comment]
Draft document here: https://docs.google.com/document/d/1fKk9iXXU6YE0URV1d5qxxOJ5UsG5RbpUbpnMo4oeHdA/edit?usp=sharing

**Comment by emcaulay** [comment]
@mark-dce and @joshuago78 , Bess and I completed a draft of this document, and in particular we would like you two to review, but also anyone and everyone from the team as well.

**Comment by joshuago78** [comment]
I added several comments. Most of them are thoughts about future changes not requested revisions to your document.

**Comment by mark-dce** [comment]
👍 
I reviewed the document & my comments are similar to Josh's - more ideas going forward than changes that need to be made to the document.

Overall the document seems really focused on *migrating collections from DLCS*.  I'm wondering if it's worth writing a new ticket to draft a document outlining the process for brand new collections like SDLP - i.e. what do I do when I don't have a DLCS export file and an existing folder of originals on a server?

**Comment by joshuago78** [comment]
I agree. We should have a separate document for importing new collections, not migrations. Ideally, we would have a generic process that could handle both, but starting with two discrete workflows is easier to tackle than trying to be all encompassing from the start.

**Comment by jendiamond** [comment]
The only thing I noticed is on e Step 7 - "I ask someone on the team to copy the CSV "

Who is "I"?

**Comment by emcaulay** [comment]
Thank you @jendiamond -- good call out!

**Comment by emcaulay** [comment]
Everybody really helped with this document -- thank you so much for your comments.

Just as a little note here, this document is really aimed at helping the team (especially the non-developer part of the team) know how to arrange all the assets and know who on the developer and dev ops teams can do which things. 

It is focused on only simple image collections and collections that are in DLCS, because that is the current work we are doing. 

I will keep working through this document to make it actionable and Josh has had a good lens on it for making the process more efficient.
