### ISSUE TITLE
Import Relation.isPartOf

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#367]
>NOTE: This is temporary scaffolding until we can do more complete collection work and refactor the importer to add items directly to Hyrax collections in Phase 2.

Add a `Collection` attribute for the `Work` class:

- [x] A Work object can have a `dlcs_collection_name` field
- [x] The predicate for it is `https://bib.schema.org/Collection`
- [x] The label for it is "DLCS Collection Name"
- [x] The field should NOT be SEARCHABLE
- [x] The field should be faceted

Given a CSV with a ~`relation.isPartOf`~ `Relation.isPartOf` column:
- [x] importing this CSV creates objects with the values in the `dlcs_collection_name` attribute.

**Comment by bess** [comment]
Done, but the data has a field called `Relation.isPartOf` (capitalized R) so I updated the ticket to reflect that instead.
