### ISSUE TITLE
Block full sized downloads from IIIF server

### ISSUE THREAD

**Issue by ksclarke** [UCLALibrary/californica#373]
We want a simple block of full sized images from the IIIF image server.

- [x] Confirm full-sized images cannot be downloaded from IIIF server

**Comment by emcaulay** [comment]
Hi @ksclarke , we're thinking you might have already completed this? We are prepping backlog grooming for the Apps Team which will have its sprint planning on Wednesday 1/9/19 and so we are going through the Waffle Board.

**Comment by ksclarke** [comment]
Yes, sorry. Just forgot to close it.
