### ISSUE TITLE
Display items on Collection page

### ISSUE THREAD

**Issue by joshuago78** [UCLALibrary/californica#387]
- Follow Hyrax implementation as a first pass at this
- We will iterate on the design once we have this starting point

**Comment by emcaulay** [comment]
@andrewbenedictwallace can you look at this ticket and determine whether it's still valid? I know we discussed during the sprint planning meeting.

**Comment by andrewbenedictwallace** [comment]
I believe it this one belongs in Ursus, but is necessary. Once we start making collections in californica, vanilla blacklight won't know how to show them, so we'll have to copy some hyrax code over to do that.

**Comment by andrewbenedictwallace** [comment]
Closing in favor of https://github.com/UCLALibrary/ursus/issues/228
