### ISSUE TITLE
On ingest, attach works to a collection

### ISSUE THREAD

**Issue by joshuago78** [UCLALibrary/californica#395]
This ticket represents a quick fix, allowing us to resume developer-led ingest of targeted collections. It does not depend on https://github.com/UCLALibrary/amalgamated-samvera/issues/256, which will determine the eventual automated ingest workflow.

Acceptance:
- [x] on ingest, records are attached to a manually-created collection object, which can be specified at ingest time and is applied to all items in a CSV
- [x] documentation is updated to describe the process of creating a collection and importing a CSV

child of #385
depends on #339

**Comment by bess** [comment]
You can see the Connell collection works attached to a collection object here: https://californica-dev.library.ucla.edu/collections/d217qp90j?locale=en

![connell_collection.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb9b942d878fa5b0eab04fa858f380204929316546b3397f8fe62bab0021435a0d4df915595b4cf5a88922f7e33c708b0e0de4d66b5e71d42103eee9dc4be05ce36ade0d97bcae8b44cae93820e689864b381a031e8ff84f78.png)

**Comment by bess** [comment]
![connell_collection.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb9b942d878fa5b0eab04fa858f380204929316546b3397f8fe62bab0021435a0d4df915595b4cf5a88922f7e33c708b0e0de4d66b5e71d42103eee9dc4be05ce36ade0d97bcae8b4bcae93820e689864b391e031b8cff4f78.png)

Screenshot on californica-dev. Note that this shot was taken partway through the job, so not all items had been added to the collection yet. Also note that the "date added" field for most of these works is 13 December 2018. These works were updated, not re-ingested.

**Comment by emcaulay** [comment]
I just checked the link and 503 items are listed under the Will Connell collection in californica-dev.
