### ISSUE TITLE
Update importer to handle collections

### ISSUE THREAD

**Issue by joshuago78** [UCLALibrary/californica#396]
Given a CSV export file:

- [ ] Importer should create a collection level record at import time if it doesn't exist yet
- [ ] If the collection level record exists already, the importer should update its metadata
- [ ] All items in the CSV should be made members of the collection

child of #385

requires https://github.com/UCLALibrary/amalgamated-samvera/issues/256

**Comment by andrewbenedictwallace** [comment]
I think this is old and deprecated, superseded by #436 and others?

**Comment by mark-dce** [comment]
Restated in #436 & #432
