### ISSUE TITLE
Ingesting a batch of images and metadata through web UI

### ISSUE THREAD

**Issue by kjallen** [UCLALibrary/californica#40]
### Story

As an content owner, I want to be able to upload images and related metadata through a web page, so that my content will be processed and added to the system

### Details

A user with sufficient permissions should be able to upload a number of TIFF image files from their workstation through the Samvera Web UI. The images will be processed, added to the repository and a status result will be presented to the user. A user will also have the option of uploading related files containing metadata about the image, in MODS XML format. A metadata file is not required.

### Acceptance

- [ ] An accurate status message is shown to the user in the web interface, success or failure.
- [ ] The original TIFF images will be available in the repository along with related derivatives, including thumbnail of the image
- [ ] The data in the uploaded metadata file will be parsed, added to the records associated with the image, and viewable in the web interface

**Comment by kjallen** [comment]
This will be revised due to increased understanding of Samvera workflow.
We will not be using MODS as an import source, nor storing the resulting MODS file in Samvera
The TIF workflow will be defined based on IIIF discussion

**Comment by mark-dce** [comment]
Superseded by 
#503 Validate CSV via browser
#504 Run the import when my CSV passes validation
and related tickets
