### ISSUE TITLE
Explicitly specify primary identifier

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/californica#400]
[This PR](https://github.com/UCLALibrary/californica/pull/399) creates a single-value field for the ark (archival resource key) identifier, so it can be used in blacklight urls. The ark is found by searching the "identifiers" field for a value that starts with "ark:"

This solution would not be suitable if a record has multiple arks – IDK if that is ever the case, but it might be useful if duplicate records are found and merged.

Instead, it might make sense to allow the system to explicitly designate one of several identifiers as the primary.

**Comment by mark-dce** [comment]
Superseded by Add an "ARK" property to the UCLA data model #456
