### ISSUE TITLE
Add ability to update work records rather than create new works - i.e. Batch Update

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/californica#403]
Acceptance criteria:
- [x] on ingest, if a record already has a given ark it will be updated, instead of creating a new record
- [x] So that we get a performance improvement over re-ingesting from scratch, provide a setting that will perform a metadata-only update
- [x] Do not re-attach images that were already attached

**Comment by emcaulay** [comment]
Is this ticket waiting for review?

**Comment by bess** [comment]
Timings for Connell sample on my local box. Jobs run in-line to accurately capture the entire time it takes to run an import.

Initial import:
 51.677027   2.483050 237.352565 (181.997587)

Re-import with full stack:
 42.863078   1.807574 225.658880 (160.216498)

Re-import with metadata-only stack:
 9.302353   0.419988   9.722341 ( 14.526300)

**Comment by bess** [comment]
Metadata-only reimport of LADNN on californica-dev took ~6 hours instead of 17. See output below and collection with content at https://californica-dev.library.ucla.edu/collections/d791sg57z?locale=en

```
I, [2019-03-05T00:45:20.492911 #18713]  INFO -- : event: finish_import, batch_id: , successful_record_count: 5173, failed_record_count: 0, elapsed_time: 24006.241228178144, elapsed_time_per_record: 4.640680693635829
```
