### ISSUE TITLE
Re-index all the Work records in Dev, Stage & Test

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/californica#407]
Connected to  https://github.com/UCLALibrary/californica/pull/409

Subsequent to https://github.com/UCLALibrary/californica/pull/406, and as a prerequisite to using arks in Ursus urls, we need to reindex all our server environments

Acceptance – all environments have been reindexed so that the single-valued solr field `ark-ssi` is available for use in Ursus urls:
- [x] californica-dev
- [x] californica-test
- [x] californica-stage

---

#### Acceptance
- [x] [Write a rake task that reindexed all the Work records](https://github.com/UCLALibrary/californica/commit/5899feb19d7caeb8bbec616ea750705629cfd5b5)

**Comment by jendiamond** [comment]
Run the rake task on the environments to re-index all the Work records
+ Use Jenkins to deploy
+ **$** `ssh deploy@californica-test`   
+ **[deploy@t-w-californicaweb01 ~]$** `cd /opt/californica/current`  
+ **[deploy@t-w-californicaweb01 current]$** `RAILS_ENV=production nohup bundle exec rake reindex 2>&1 > reindex.log &`    
+ **[deploy@t-w-californicaweb01 current]$** `tail -f reindex.log`  
---
- [x] dev
Log
```
No GeoNames credentials provided. Set `geonames_username` in Hyrax configuration.
Re-index started at: 2019-02-22 07:52:34 -0800
Re-indexing 0 Collection records: 2019-02-22 07:52:34 -0800
Re-indexing 5777 Work records: 2019-02-22 07:52:34 -0800
Re-index finished at: 2019-02-22 10:00:10 -0800
Re-index finished in: 127.6 minutes 
```
---
- [x] test
Log
```
[deploy@t-w-californica01 current]$ tail reindex.log
No GeoNames credentials provided. Set `geonames_username` in Hyrax configuration.
Re-index started at: 2019-02-21 14:58:34 -0800
Re-indexing 1 Collection records: 2019-02-21 14:58:35 -0800
Re-indexing 5677 Work records: 2019-02-21 14:59:47 -0800
Re-index finished at: 2019-02-21 17:12:12 -0800
Re-index finished in: 133.6 minutes
```
---
- [x] stage
```
No GeoNames credentials provided. Set `geonames_username` in Hyrax configuration.
Re-index started at: 2019-02-22 11:56:12 -0800
Re-indexing 0 Collection records: 2019-02-22 11:56:13 -0800
Re-indexing 5173 Work records: 2019-02-22 11:56:13 -0800
Re-index finished at: 2019-02-22 14:00:13 -0800
Re-index finished in: 124.0 minutes 
```
