### ISSUE TITLE
Re-index all the Work records in Production

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/californica#412]
This requires pieces in Ursus to be working.

Subsequent to https://github.com/UCLALibrary/californica/pull/406, and as a prerequisite to using arks in Ursus urls, we need to reindex all our server environments

Run the rake task on the environments to re-index all the Work records
+ Use Jenkins to deploy
+ **$** `ssh deploy@californica-prod`   
+ **[deploy@p-w-californicaweb01 ~]$** `cd /opt/californica/current`  
+ **[deploy@p-w-californicaweb01 current]$** `RAILS_ENV=production nohup bundle exec rake reindex 2>&1 > reindex.log &`    
+ **[deploy@p-w-californicaweb01 current]$** `tail -f reindex.log`  

Acceptance – all environments have been reindexed so that the single-valued solr field `ark-ssi` is available for use in Ursus urls:
- [ ] californica-production
Log
```

```

**Comment by emcaulay** [comment]
This ticket is sitting in "For Release", but I cannot tell what the next step is. Has the re-indexing already taken place on all environments?
