### ISSUE TITLE
Document californica internal ingest process

### ISSUE THREAD

**Issue by joshuago78** [UCLALibrary/californica#423]
As a software architect I would like a document outlining the steps taken by Hyrax during the ingest of an item, calling out which steps are blocking or non-blocking, and which are configurable or have hooks to easily change the called process

**ACCEPTANCE**
- [x] Document is reviewed by @joshuago78

**Comment by val99erie** [comment]
Here are a couple documents that will help:

https://docs.google.com/presentation/d/1dt6BLb7OxkNOS1rUOAakhXzUUasv3CWNPwcxmA4TeL0
and
https://docs.library.ucla.edu/display/CUP/Californica+CSV+Importer+Notes

**Comment by emcaulay** [comment]
Thanks, @val99erie. I left a comment on the Confluence doc.

**Comment by val99erie** [comment]
I updated the confluence document.

**Comment by joshuago78** [comment]
Thanks @val99erie . This is excellent!
