### ISSUE TITLE
Enable Librarians to select representative image for a collection

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#427]
As a librarian, I would like to select a representative and effective image to be associated with a collection in any display of that collection level record. This image will act as a visual proxy for the collection. I would like to do this activity through the staff web interface.

**Acceptance Criteria**
As a logged in user with admin privileges
- [x] There is a workflow / UI to allow me to associate an image from the collection with the collection level record
- [x] After selecting the representative image, I can view the search results that include the collection level record and see the thumbnail of the image I selected
- [x] After selecting the image, I can change my selection if I decide I don't like it

**Comment by little9** [comment]
Here's a video of how this works:
https://github.com/little9/little9.github.io/blob/master/images/collection.mp4

**Comment by emcaulay** [comment]
Looking forward to watching this!
