### ISSUE TITLE
Show collection thumbnails in search results

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#429]
**STORY**
As a collection owner, want the same collection image to show up in search results that shows up in the collection dashboard, so that users have a visual proxy for the collection.

**ACCEPTANCE**
When a collection has a thumbnail set
- [x] The collection't Thumbnail is displayed in search results

Dashboard Current Behavior
=================
https://californica-test.library.ucla.edu/dashboard/my/collections?locale=en  

<img width="749" alt="image" src="https://user-images.githubusercontent.com/3064318/53899087-01bec280-3fff-11e9-82c3-d8c2d14764f9.png">

Search Results
===================
https://californica-test.library.ucla.edu/catalog?utf8=✓&locale=en&search_field=all_fields&q=Los+Angeles+Daily+News+Negatives  

<img width="998" alt="image" src="https://user-images.githubusercontent.com/3064318/53899195-464a5e00-3fff-11e9-8a83-61e146dbdd5d.png">

Child of #385

**Comment by andrewbenedictwallace** [comment]
Collection thumbnails not showing is a known hyrax bug with a fix in hyrax as of v3.0.0.pre.beta2.

We* are using 2.3.3 but could backport the fix to hyrax 2: https://github.com/samvera/hyrax/pull/3291

* (I haven't signed the contributer agreement but would love to watch a dce person do it!)

**Comment by bess** [comment]
I've submitted a backport PR here: https://github.com/samvera/hyrax/pull/3658
Once that is merged we'll have to get a 2.4.2 release out and then we'll need to upgrade to that version.

**Comment by bess** [comment]
This backport has been merged. Monday I'll ask for a 2.4.2 release of Hyrax.

**Comment by bess** [comment]
I released  v2.5.0 of Hyrax today, which should address this. PR waiting for merge.

**Comment by bess** [comment]
Fixed! Screenshot from Hyrax 2.5.0 on californica-dev:

![collections_with_thumbnails.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb9b962f8780bd86e6b1509b4af9802179337b3c09a125718cef3bfd0e39111d0014f9121c4d4eeefcdb28f3e23d7482555aedd83c0a74c63c43aab18519be04a83c990dd4e8e8d51199a26867f5819d4d3f14041d8cfd5431a3914fc85df34bf300.png)
