### ISSUE TITLE
Add UCLA metadata fields to collection edit form

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#430]
**STORY**
We've added the UCLA metadata fields like `caption` and `normalized_date` to the collection object model, but users can't currently edit them in the UI.

**ACCEPTANCE**
- [x] The properties in https://github.com/UCLALibrary/californica/blob/master/app/models/ucla_metadata.rb should be editable in the collection edit form

**Comment by bess** [comment]
While working on this I noticed that there are two fields labeled "Location" -- one of these is the Hyrax "based_near" location, and the other is the UCLA `::RDF::Vocab::DC.coverage`Location -- I'm going to open a separate ticket to fix this.

**Comment by emcaulay** [comment]
I can verify that I was able to enter more metadata into the Collection records for LADNN and Will Connell collections.
