### ISSUE TITLE
Add UCLA metadata to collection show view

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#431]
**STORY**
We've added the UCLA metadata fields like `caption` and `normalized_date` to the collection object model, we need to ensure they show up on the collection view pages.

**ACCEPTANCE**
When the properties in https://github.com/UCLALibrary/californica/blob/master/app/models/ucla_metadata.rb are populated with values
- [x] They appear on the collection show page `./collections/[id`]
- [x] They appear on the collection dashboard show page `./dashboard/collections/[id]`

Child of #385

**Comment by bess** [comment]
Screenshot on californica-dev of metadata on `./collection/[id]` page:
![collection_metadata.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb9b962f8780bd86e6b17ca958e4952d4733726b48e13b628ae92dbc56395b4d5a1caf140c5e40f4f0d82bafe769708a5d59ebd86a5975c32f0dbefad341eb5ee779c11ac7a4b6984ec0e23c20e2898c4e3c1605118cfd5d27ed.png)

**Comment by bess** [comment]
Screenshot of the same collection on `./dashboard/collections/[id]`:
![collection_metadata_on_dashboard.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb9b962f8780bd86e6b17ca958e4952d473372160bad147484f020bd4d7a130b4d52be011a001ea9aacd39aca4392289095fecd5655625c63440f9b8821eed07b3278d4e80a4a0980e91b6697abad2c51a7c0c0f0a88f75734a59c49cb59f24ee84555a010242e.png)
