### ISSUE TITLE
Update ingest process to add works to a collection

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#432]
**ACCEPTANCE**
When my import CSV has a column with a collection-ark in it
- [x] The corresponding work is added to the collection
   - [x] If a collection with the collection-ark doesn't exist, a new collection with that ark is created
  - [x] Automatically created collections have default metadata so they can be opened in the edit UI without errors.
 

Child of #385

**Comment by mark-dce** [comment]
I've mocked up a proposal that calls the column "Parent ARK" - for Works, that would be the ARK of the collection that contains the work.  For manuscript pages (or any child work) that would be the ARK of the parent work.  
https://gist.github.com/mark-dce/550cfe5b2f63afe4ca06cd2f4adca04c

The downside is that sometimes that column holds a collection ARK and sometimes its a work ARK.  Either way, it's the ARK of the repository object the current row should be added to.  The upside is it eliminates ambiguities that could occur on page-level records if we had both a "Collection ARK" and "Parent ARK" column.  I.E. having both columns could allow us to enter a different collection ark for a page than for the work that contains that page.

**Comment by emcaulay** [comment]
Hi @val99erie , Please see UCLALibrary/AmalgamatedSamvera#435

**Comment by mark-dce** [comment]
FYI - I added another acceptance criteria / clarification - if we automatically create a collection, I'm pretty sure we need to save the collection object with the minimal required metadata otherwise it may throw an error in the edit form.  Even if that's not the case, we should probably supply a generic title because it gives a more obvious way to edit  the collection.

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/3064318/54657238-ad9fed80-4a96-11e9-8fed-e8e116ae0215.png">

**Comment by val99erie** [comment]
CSV with `Parent ARK` field can now be used to add the works to a collection.

**Comment by emcaulay** [comment]
Great news!
