### ISSUE TITLE
Add a link to the same item in ursus

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#434]
**STORY**
As a librarian viewing a work in californica, I'd like an easy way to find the same work in ursus, so that I don't have to cut and paste IDs into URLs

**ACCEPTANCE**
- [x] there is a link to "View this work in ursus" underneath the viewer and before the metadata on the work and collection level show page

**Comment by val99erie** [comment]
We'll need to add a new environment variable to all 4 of the Californica environments.  This env var will tell Californica how to find the corresponding Ursus environment, so we're just setting it to the Ursus domain name.

The environment variable is called: `URSUS_HOST`.

- [ ] For the Californica dev env, set it to: `ursus-dev.library.ucla.edu`

- [ ] For the Californica test env, set it to: `ursus-test.library.ucla.edu`

- [ ] For the Californica staging env, set it to: `ursus-stage.library.ucla.edu`

- [ ] For the Californica production env, set it to: `ursus.library.ucla.edu`

@croft103 - Can you add these environment variables for me?  If you need more info, just ping me in Slack, and we can chat about it.  I'll be out of the office on Monday, but we can talk on Tuesday.

**Comment by val99erie** [comment]
@bess - For the DCE californica env, we'll need to add this env var too.  Please see the comment above.

**Comment by croft103** [comment]
I'll have a look at the ansible script to integrate these environment variables across the servers.

**Comment by croft103** [comment]
@val99erie the environment variable has been added in ansible and pushed out to the 4 servers. Does Apache need to be restarted to pick this up?

**Comment by croft103** [comment]
@val99erie Apache has been restarted on the servers. Your request has been completed, but I'm not sure if that closes this ticket. Let me know if there is anything else I can do.

**Comment by val99erie** [comment]
@croft103 Yes, it looks like everything is working perfectly.  Thanks for the help!
