### ISSUE TITLE
Delete and regenerate all derivatives in Californica Prod

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#437]
As a nervous and fastidious librarian, I would like to clear out all our derivatives and regenerate the derivatives. Per discussion on californica #413

**Acceptance Criteria** 
- [x] Items with corrupt files no longer display an incorrect thumbnail image, they instead display a placeholder.
  - [x] Test object on californica-test:
https://californica-test.library.ucla.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=zz0027xj0t
  - [x] Test object on californica-prod: https://californica.library.ucla.edu/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=zz0027xj0t

**Comment by bess** [comment]
@cachemeoutside This is what I did to fix this on californica-test. The same procedure needs to be done on californica-prod by someone with command line access there.

1. Log in as the deploy user
2. rm -rf /opt/derivatives/*
3. cd /opt/californica/current
4. RAILS_ENV=production bundle exec rake derivatives:regenerate_all

Let's make sure this fixes the problem on -test first (I'm running that now... the regenerate derivatives job will take a few hours) and if it does then you can run this procedure on prod at your convenience.

**Comment by bess** [comment]
My job on californica-test is failing because the disk is full. @cachemeoutside When you're back would you please take a look at this?

**Comment by bess** [comment]
I am glad we tried this on -test first. The re-generate derivatives job keeps filling up `/opt/uploads`. The first time I thought it was a fluke, but it just happened a second time so for sure it's the regenerate derivatives job that's doing it. I'm going to refactor that job so it cleans up after itself so this stops happening.

**Comment by bess** [comment]
Before:
![wrong_thumbnail_on_test.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46ff86952d85bcbd87fcb241aa5cf9981649294c3d01b03f32c9a138ad4d71040c1b5ca6535d0d47a9ad882faebf6d70830d5eedd16c0d72cf3a17adbd9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3b1c05118ffe5f34a39e48da15.png)

After:
![after_regenerate_derivatives.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46e9928e2690bcbb8aeeba4da14ff1802c7923763b0db52a648cf52dac0037431f1d11f6140b1b56f6eb8c79a5e368718e5402bcd1640e21c63d10febe8b18b900bf32975dc7e7e2de139db17770a599855d3f170f198cfa5f35a99f4acb5afe49e05f18.png)

**Comment by croft103** [comment]
@bess I ran the rake job on production but it continued to fill up /opt/uploads without any apparent cleanup. I guess I wasn't clear on if the refactoring was complete and pushed to production. Please advise.

**Comment by bess** [comment]
@croft103 Sorry for the miscommunication. I was hoping we'd get to talk about this before you ran it in production. Get in touch when you're in this morning (Monday) and let's make a plan.
