### ISSUE TITLE
SPIKE: How can we backup and restore californica-prod?

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#441]
As a DevOps engineer, I need a quick, easy, and repeatable way to recover from data corruptions. We need to make a plan for how we'll manage this for the following parts of the repository:
- [ ] On the production management environment
    - [ ] Solr Index
    - [ ] Database
    - [ ] Shared images
    - [ ] Fedora
    - [ ] Redis
    - [ ] Other system state

Other acceptance criteria:
- [ ] All backups must be in sync with each other (possibly a window during which the system is in read-only mode?)
- [ ] We need a place to restore to (Possibly we can use the stage environment for this? How hard will it be to spin up a new environment?) 
- [ ] We need written documentation for how to perform a data restore
- [ ] Documented decision about how frequently backups happen
- [ ] The rest of the team needs to know when backups happen so they aren't trying to ingest data at that time

**ACCEPTANCE CRITERIA**
- [ ] We have a plan for how all of the above will be accomplished
- [ ] We have tickets written for implementing the plan

Child of #274

**Comment by croft103** [comment]
As a first step to better understand all the pieces and dependencies in our production environment, I will spin up a single server to learn what is required to execute a restore of prod to this server.

**Comment by mark-dce** [comment]
Superseded by
#484 Restore californica-test environment to samtest
#563 Document a backup/restore procedure for Californica in the UCLA environment
