### ISSUE TITLE
Revise Local Identifier export and import

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#444]
While working on a story about where local identifier gets mapped (#435), I realized that the Californica mapper is expecting local identifier to be in a field called `Alternate Identifier.local`, because that's where it was in the initial data samples we used for fixture objects. However:
* the Connell spreadsheet we've been loading has that field instead labeled `Alt ID.local`

**ACCEPTANCE CRITERIA**
- [x] We agree on a heading for the local identifier field
- [x] This heading does not change for future data exports
- [x] The californica metadata mapper is updated to match that heading (Update: the heading will be `AltIdentifier.local` per @emcaulay's comment below)
- [x] New CSV exports are created that use the updated heading

**Comment by emcaulay** [comment]
I don't think I would call this a bug. It's a feature! Sorry, bad joke, but it is true. It's an accurate output of one of the features that DLCS had: the ability to customize the labels of the metadata fields. I have put in a ticket to have the DLCS export script use the canonical field name and not the per-project-customization.

**Comment by emcaulay** [comment]
Assigned to @kjallen  and tracked here: https://jira.library.ucla.edu/browse/DLCS-512

**Comment by emcaulay** [comment]
@bess , please see the Bennett CSV. The canonical output going forward will be "AltIdentifier.local". Is this okay?

**Comment by bess** [comment]
@emcaulay It can be whatever we want it to be as long as we settle on something and don't change it for each new export. So sure, that's fine. We will update the importer mapping accordingly.
