### ISSUE TITLE
Add metadata field "rights" to Californica

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#447]
As a librarian, I want to make sure all the metadata from the Will Connell collection is migrated to Californica. Unlike the LADNN, the Will Connell collection does not use a Creative Commons license. Therefore a string value for the rights statement is required. At the moment, UCLA does not use rightsstatements.org so a string is required.

Add metadata field "rights" to Californica with predicate "dce:rights" for all types of objects in Californica.

**Acceptance Criteria**
- [ ] A new metadata field is added to Californica to support entry of a string value for a rights statement. The predicate identified for this metadata field is dce:rights.

note: Needed for Will Connell collection to complete metadata

**Comment by bess** [comment]
Just double checking... you want a `rights` field that's separate from the `rights_statement` field that's already standard? All Connell materials already have a `rights_statement` field that's set to a UCLA specific value ("http://vocabs.library.ucla.edu/rights/copyrighted") which displays on the UI as "copyrighted". 

Here is what that looks like in RDF:
`  <http://www.europeana.eu/schemas/edm/rights> "http://vocabs.library.ucla.edu/rights/copyrighted";
`

And here it is on the console:
```
=> #<Work id: "kp78gg65x", head: [#<ActiveTriples::Resource:0x5fac634 ID:<http://t-u-californicafedora01.library.ucla.edu/fcrepo/rest/prod/kp/78/gg/65/kp78gg65x/list_source#g76924360>>], tail: [#<ActiveTriples::Resource:0x706bd6c ID:<http://t-u-californicafedora01.library.ucla.edu/fcrepo/rest/prod/kp/78/gg/65/kp78gg65x/list_source#g76924360>>], depositor: "batchuser@example.com", title: ["Asian-looking man, probably in Will Connell's photography studio, 1930-1960"], date_uploaded: "2018-12-14 20:15:17", date_modified: "2019-03-11 14:59:49", state: #<ActiveTriples::Resource:0x5fbf338 ID:<http://fedora.info/definitions/1/0/access/ObjState#active>>, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksum: nil, owner: nil, extent: ["1 photographic negative"], caption: ["Text from negative sleeve: David / Chinaman / Colonel Otto"], dimensions: [], dlcs_collection_name: ["Will Connell Collection. Department of Special Collections, Charles E. Young Research Library, UCLA."], funding_note: ["Access to this collection is generously supported by Arcadia funds."], genre: ["cellulose nitrate film", "black-and-white photographs"], latitude: [], location: [], local_identifier: ["uclamss_893_0413"], longitude: [], medium: ["b&w nitrate negative"], named_subject: [], normalized_date: ["1930/1960"], photographer: ["Connell, Will, $d 1898-1961"], repository: ["University of California, Los Angeles. $b Library Special Collections"], rights_country: [], rights_holder: [], label: nil, relative_path: nil, import_url: nil, resource_type: ["still image"], creator: [], contributor: [], description: ["Bust-length photographic portrait of an Asian-looking man smoking a cigarette (?) and wearing a dark Chinese style jacket"], keyword: [], license: [], rights_statement: ["http://vocabs.library.ucla.edu/rights/copyrighted"], publisher: [], date_created: ["[between 1930-1960]"], subject: [], language: [], identifier: ["21198/zz002h2pvs"], based_near: [], related_url: [], bibliographic_citation: [], source: [], access_control_id: "d825c27d-8dfb-4f7e-a7b1-4839042a0236", representative_id: "hx11xf65s", thumbnail_id: "hx11xf65s", rendering_ids: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>
irb(main):006:0> work.rights_statement
=> ["http://vocabs.library.ucla.edu/rights/copyrighted"]
```

**Comment by emcaulay** [comment]
I believe I misunderstood the field name as being connected specifically to the controlled values developed and maintained at rightsstatements.org. Reading your comment and reviewing the above example educates me and I do not need additional rights fields at this time.
