### ISSUE TITLE
Train Tinu to do Releases

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/californica#449]
- [x] Add Tinu to Jenkins
- [ ] Go through the process several times  
[Release Manager Notes](https://github.com/UCLALibrary/amalgamated-samvera/wiki/Release-Manager-Notes)   
[Release Checklist](https://github.com/UCLALibrary/amalgamated-samvera/wiki/Release-Checklist)

**Comment by croft103** [comment]
@jendiamond, Tinu is setup with access to Jenkins and the appropriate projects.
