### ISSUE TITLE
On Californica servers point /opt/uploads off the root partition

### ISSUE THREAD

**Issue by croft103** [UCLALibrary/californica#454]
This has been done on Prod using the NFS mounted NetApp space (1TB): /opt/uploads -> /opt/derivatives/uploads (owned by deploy:deploy). Do this on:

- [x] d-w-californica01

- [x] t-w-californica01

- [x] s-w-californicaweb01

- [x] p-w-californicaweb01

/opt/uploads is used when regenerating derivatives. Depending on the size of the input, this may cause the partition to fill. Cleanup is executed periodically via cron.

**Comment by croft103** [comment]
@bess I made a symlink from /opt/uploads to the /opt/derivative/uploads mount point across the servers, but then thought better of this; it will be reflected across our ansible scripts, and the solution was a bit of a stopgap measure.

Can you clarify how the /opt/uploads directory is used? My understanding is that it was for a manual upload process, which we currently don't use. In our current environment it does not appear to get cleaned out regularly. It did get used by the by the rake job to recreate derivatives, is that a proper use? The required capacity needs to be at least equivalent to what is being ingested.

I guess the short question is, should this really be another mount point from the Netapp so it's not nested within the derivatives space?

**Comment by bess** [comment]
The `/opt/uploads` directory is used:
1. When a file is added to a work via the UI. This will rarely, if ever, happen for UCLA according to current plans.
2. When derivatives are re-created manually. Again, this will rarely, if ever happen. The fact that we had to do it was the result of having data that had been re-loaded several times, combined with the fact that @sgurnick and I did not clean out `/opt/derivatives` between data loads, combined with the fact that there were corrupt images in the data that we were loading. Only in the case of all three of those being true was it necessary to re-generate all of the derivatives and I very much hope we will never encounter that situation again.

I think it's totally possible that we do not need for `/opt/uploads` to have any special treatment at all as it will rarely, if ever, be used. 

I also believe that `/opt/uploads` *does* get cleaned out regularly, or at least we have code in place that should be doing that. See https://github.com/UCLALibrary/californica/blob/master/config/schedule.rb#L35. If you think it is not getting cleaned out I'd like to talk about why that job might not be running as expected.

**Comment by croft103** [comment]
@bess, by no special treatment, do you mean leave /opt/uploads symlinked to /opt/derivatives/uploads and be done with it?

You are correct that a cleanup cron is enabled on dev, test, stage, prod. However, the 'find' command needs a '-L' to follow the symlink. It's also deleting only files, but leaving  the directory structure.

**Comment by bess** [comment]
Yes, I would leave it symlinked and be done with it

Also, good catch on the cleanup task... I will fix that.

**Comment by croft103** [comment]
Great, thank you.
