### ISSUE TITLE
Ensure items are imported with an 'ark:/' prefix

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#457]
**ACCEPTANCE**
Given a CSV import file with a column headed "Item Ark",
- [ ] Import the value in the column to the `ark` property of the work or collection
- [ ] Prepend the string 'ark:/' to the value in the field if it's missing

Requires #456 

Child of UCLALibrary/ursus#270

**Comment by mark-dce** [comment]
Note, we may have to check and replace ark: with ark:/

**Comment by val99erie** [comment]
I recently added a method that might help with this.  For examples, search the code for: `Ark.ensure_prefix`.
https://github.com/UCLALibrary/californica/blob/master/app/services/ark.rb#L7
