### ISSUE TITLE
Implement a read-only mode

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#462]
As someone who cares about data preservation, I want a read-only mode for the system. When californica is in read-only mode it can still be searched and ursus will will be able to read from californica, but no changes can be made. This will create a safe window during which backups can be performed.

- [x] There is a feature flipper that will turn read only mode on and off
- [x] When read-only mode is in effect there is a banner telling me why I can't add or edit records
- [ ] I can put the system into read-only mode via a cron job, so I can automate backups

Child of https://github.com/UCLALibrary/californica/issues/274

**Comment by mark-dce** [comment]
NOTE: Penn State and DCE have example code to provide this functionality

**Comment by jendiamond** [comment]
@val99erie ppointed me at this: https://github.com/curationexperts/laevigata/blob/master/lib/tasks/read_only.rake

**Comment by jendiamond** [comment]
![Screen Shot 2019-03-20 at 10.23.20 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f36b7191a379ef0c2952415d4ebc30254d58eeb9cb74fce36f34985619e8836e0a20c73919a5e98216ee54ba208a1d83bfbb8c4dc5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee24c55a615326bef76366e0a.png)
