### ISSUE TITLE
Run the importer for Bennett Collection in staging

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#474]
Run the importer for Bennett
 - [x] Staging
 - [x] @emcaulay -- Review collection in staging, and repeat importer until collection (metadata and images) are approved

Requires #464
Requires #471
Requires #472
Requires #475

**Comment by bess** [comment]
```
I, [2019-04-01T14:24:42.685318 #118242]  INFO -- : event: finish_import, batch_id: , successful_record_count: 79, failed_record_count: 0, elapsed_time: 1541.1243684591027, elapsed_time_per_record: 19.50790339821649
```

https://californica-stage.library.ucla.edu/collections/zz00011f8m-21198

**Comment by emcaulay** [comment]
Bess and I reviewed together today, and the original CSV is not in proper UTF-8 so we will wait for a new export and then re-import to stage.

**Comment by emcaulay** [comment]
Lisa has requested a new CSV export from @kjallen via https://jira.library.ucla.edu/browse/DLCS-524.

**Comment by emcaulay** [comment]
@bess , We have a new CSV with UTF-8 data: https://ucla.box.com/s/319zmjmz970r44lmw0atrh3wkpj465lv.

**Comment by bess** [comment]
This has been run and the character encoding problem seems to have been solved. See, e.g., https://californica-stage.library.ucla.edu/concern/works/zz0009gwqr-21198

**Comment by bess** [comment]
![yameogo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46f19597268d84a6cda5fd53b652fa912a5265296b51a1787581b27ce71b7a51560e1bac41590d42f5fe8f2aa3a42062c80d55b98e30063e937f03a6aa8317b500bf258f4c85b4bb8a44c4e03a37aa.png)
