### ISSUE TITLE
Copy approved Bennett CSV to opt/data

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#475]
As a team member, I would like to make sure that once the CSV for Bennett is completed and approved by the metadata team, that it is moved into the actionable location for the developers. 

Child of #465
Requires #473
Requires #472

**Comment by emcaulay** [comment]
@croft103 , the file is available on box: https://ucla.box.com/s/319zmjmz970r44lmw0atrh3wkpj465lv. 

I think it's possible other team members can copy this file to the right location, but I cannot.

**Comment by bess** [comment]
The above referenced file gives these errors when I try to run it: 
```
"The CSV file contains unknown columns: Parent Ark, Object Type, File Name, Name.creator, Rights.permissionNote, Rights.servicesContact, Rights.permission, Description.abstract", lineno=nil>
```

I'm going to fix the headings to something that Californica 1.4.0 can handle and import that version.
