### ISSUE TITLE
Add `extent` to the bulk importer

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#48]
**ACCEPTANCE**
Give a MODS import file with a `extent` term,
- [ ] The imported object displays the extent on the show page

*NOTE:* faceting and other behaviors are outside the scope of this ticket.  Those requirements will be addressed in future tickets.

**Comment by ksclarke** [comment]
Metadata information for `extent`: https://docs.google.com/spreadsheets/d/1muoNt40y7nKPlthOr_CwuvvXdQLM2uYhEu55GXhASnU/edit#gid=0
