### ISSUE TITLE
Mount entire `masters` volume to /opt/data

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/californica#483]
Acceptance criteria:

- The entire netapp `masters` volume is mounted (read-only!) at `/opt/data/masters` (or similar) for each environment:
  - [x] dev
  - [x] test
  - [x] stage
  - [x] prod
- [x] Delete previously copied master images from `/opt/data` (same volume is mounted to all environments)
- Documentation is edited to reflect the change in IMPORT_FILE_PATH
  - [x] Californica readme / wiki?
  - [ ] Whatever was produced here https://github.com/UCLALibrary/californica/issues/361?
  - [ ] ?

**Comment by croft103** [comment]
@andrewbenedictwallace the current mount at /opt/data is r/w. Is this writable only so the .csv files can be deposited there? I.e., nothing else in the process needs to write to this location? Is the location of the csv file set in the application or an environment variable?

**Comment by croft103** [comment]
I've proposed a solution with CoreOps to mount 'masters' read-only in the 'californicaingest' namespace on the NetApp. This would still allow write access at the root mount point were the csv files are placed. I'm waiting to hear back.

**Comment by andrewbenedictwallace** [comment]
I was imagining that /opt/data would be writable but include /opt/data/masters read-only, but it's all flexible and controlled by environment variables, so go ahead and organize it in whatever way works!

**Comment by emcaulay** [comment]
Note to all --> the original masters directory will contain corrupt files. Please make sure these are not silently loaded into Californica.

**Comment by croft103** [comment]
Masters are now mounted (ro) on /dev/opt/Masters on dev, test, stage, prod

These files/subdirectories exist on /dev/opt:
connell/
connell_sample.csv
connell_sample_images/
connell_sample_images.tar.gz
connell.tar.gz
dlcs_connell_20181204.csv
dlcs_connell_fix_local_identifier_field.csv
dlcs-ladnn-2018-09-06.csv
dlcs-ladnn-2018-10-01.csv
dlcs-ladnn-2018-10-01_utf8.csv
dlcs-ladnn-2018-10-15.csv
dlcs-ladnn-2018-10-26.csv
dlcs_ladnn-2018-12-12.csv
ladailynews/
missing_image.csv
nohup.out
sample.csv

Can someone that knows delete the files/folder that are no longer needed, or indicate here what you would like me to delete?

**Comment by andrewbenedictwallace** [comment]
Looks good! I'll finish up the ticket!

**Comment by andrewbenedictwallace** [comment]
Updated documentation in the californica readme and this google doc: https://docs.google.com/document/d/1fKk9iXXU6YE0URV1d5qxxOJ5UsG5RbpUbpnMo4oeHdA/edit#
