### ISSUE TITLE
Restore californica-test environment to samtest

### ISSUE THREAD

**Issue by croft103** [UCLALibrary/californica#484]
Preparation:
- [x] Create all-in-one restore environment samtest.library.ucla.edu
- [x] Put californica-test in read-only mode
- [x] Copy fedora-data from californica-test 
- [x] Backup MySQL database
- [x] Backup Solr
- [x] Backup Redis
- [x] Backup Derivatives
Read-only mode was enabled for all of the above steps. The copy of fedora-data was taken from a NetApp snapshot generated during the quiescent (read-only) state. How can we determine if the component parts are in a self-consistent state?

Restore:
- [x] Restore all data/databases to samtest

- [x] Does logging appear normal during start-up?
- [x] Does the visual comparison of   
https://samtest.library.ucla.edu/ (not-secure but safe) with   
https://californica-test.library.ucla.edu/   
look correct?
- [x] Reviewer - Bess :tada: :champagne: 
- [x] Reviewer - Jen 🐸
- [x] Other reviewer - Mark

** Keep in mind that Californica code base for samtest is March 18, 2019 and californica-test is April 8, 2019. We are concerned with internal content integrity, not layout or difference in function as result of the version difference.

**Comment by croft103** [comment]
@bess this is the piece of the puzzle I intend to work on. I'm happy to have any of your input.

**Comment by bess** [comment]
@croft103 I think this looks great, but I think it's going to be difficult to determine if Fedora is in an inconsistent state without restoring the rest of the application too

**Comment by mark-dce** [comment]
Mark's review:
- [x] Object count: 5677 both environments
- [x] Ids match on each environment
- [x] Matching metadata on each environment (except host)
  * https://samtest.library.ucla.edu/concern/works/s4655g86q.ttl
  * https://californica-test.library.ucla.edu/concern/works/s4655g86q.ttl
