### ISSUE TITLE
Set californica-dev admin@example.org password to match other environments

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#485]
**STORY**
As a team member, I would like passwords for shared accounts to match on all environments.

**ACCEPTANCE**
- [x] californica-dev uses the same password as californica-test and californica-stage use for admin@example.com
- [x] Update the ansible role that builds the server appropriately
- [x] confirm the login information listed under "UCLA Environments:" at https://docs.library.ucla.edu/pages/viewpage.action?spaceKey=pm&title=Samvera+Project+Handbook

**Comment by croft103** [comment]
@bess  -- a couple questions:

I can change the deployment variable for californica-dev to match the other servers, but this will not change the password on our current dev instance. If the '.env.production' file is updated, how do these variables get used and stored? I assume some sort of rake task must be run?

Arguably the dev environment should be deployed with a different password, then changed. Is there a password changing  feature from within the Californica interface? I couldn't find one.
