### ISSUE TITLE
Add `subject` to the bulk importer

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#49]
**ACCEPTANCE**
Given a CSV import file with a `Subject` term,
- [ ] The imported object displays the subject on the show page
- [ ] Multivalued subjects are added when the source has multiple values separated by `|~|`

*NOTE:* faceting and other behaviors are outside the scope of this ticket.  Tracking the source of the vocabulary will also be addressed in a future ticket: for now, treat the subject as a simple string.  Those requirements will be addressed in future tickets.

**NOTE**
See example subjects in [box: dlcs-ladnn-2018-08-10.csv](https://ucla.box.com/s/3z7x6humyhdqpeeq4lwe3xgg5qxx004a).

**Comment by ksclarke** [comment]
I believe my changes from yesterday have completed this ticket. I can import a test CSV file and see it in `rails c`:
```
irb(main):004:0> Work.find('pc289j04q')
ActiveFedora: loading fedora config from /home/vagrant/californica/config/fedora.yml
ActiveFedora: loading solr config from /home/vagrant/californica/config/solr.yml
Attempted to init base path `dev`, but it already exists
=> #<Work id: "pc289j04q", head: [], tail: [], depositor: nil, title: ["Protesters with signs in gallery of Los Angeles County Supervisors hearing over eminent domain for construction of Harbor Freeway, Calif., 1947"], date_uploaded: nil, date_modified: nil, state: nil, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksum: nil, owner: nil, genre: [], extent: [], label: nil, relative_path: nil, import_url: nil, resource_type: [], creator: [], contributor: [], description: [], keyword: [], license: [], rights_statement: [], publisher: [], date_created: [], subject: ["Transportation", "Express highways--California--Los Angeles County--Design and construction", "Demonstrations--California--Los Angeles County", "Government", "Eminent domain--California--Los Angeles", "Interstate 10", "Activism"], language: [], identifier: ["21198/zz0002nq4w"], based_near: [], related_url: [], bibliographic_citation: [], source: [], access_control_id: "43be7cfd-787a-4b14-b5e5-b9623bc6b69c", representative_id: nil, thumbnail_id: nil, rendering_ids: [], admin_set_id: nil, embargo_id: nil, lease_id: nil>
```
I didn't do anything specific to have `|~|` be the delimiter so I'm guessing this is a DCE defined delimiter and that by using it we've gotten our subject string to split correctly? `|~|` isn't really searchable in Darlingtonia's code though so I'm still trying to confirm this.

**Comment by ksclarke** [comment]
Nevermind, found it in the code I copied from Darlingtonia:

`DELIMITER = '|~|'`

**Comment by ksclarke** [comment]
Er, correction... it was an addition Tom made: https://github.com/UCLALibrary/californica/commit/c608a94d7d31ed7d706688e7d5424e4ff4bf11c3#diff-570db2005f0aaeda38928dbe1124b9b2
