### ISSUE TITLE
Document component versions for next UCLA release

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#50]
**ACCEPTANCE**
For the release planned for UCLA infrastructure
- [x] Update the [Savmera Component Stack](https://docs.google.com/spreadsheets/d/1oNsfa0EJk_PLZtD0AlbFwAnSe6DQuYuug0PIDWPaeFI/edit#gid=0) spreadsheet to reflect versions planned for the initial UCLA release

**Comment by mark-dce** [comment]
@hardyoyo & @sgurnick Can you two review the linked spreadsheet and give a thumbs up or any suggestions for improvement.  I'd love to call this ticket closed at the end of Sprint 2.

**Comment by ksclarke** [comment]
I'm curious about column B in the linked spreadsheet. How were those values decided?

**Comment by sgurnick** [comment]
@mark-dce I included a column to the far right side including what I have currently installed for the environment running within the UCLA infrastructure. Please feel free to merge this within the sheet, or to open discussions about each item.

**Comment by hardyoyo** [comment]
@ksclarke I believe Column B represents DCE's guidance/opinion. @mark-dce is that correct?

**Comment by ksclarke** [comment]
I wonder about the usefulness of UCLA Dev and UCLA Prod columns. The UCLA dev will match prod once the production ansible roles are done. What might be more useful to track is UCLA prod vs. DCE prod(?) I'm just wondering how we track version updates in the larger community and think DCE's roles might be a bellweather for us(?)

**Comment by hardyoyo** [comment]
I think the comparison is for current dev versions vs. prod in progress, this document does not represent any sort of policy or decision, it's helping us make decisions.

**Comment by ksclarke** [comment]
But there are multiple current dev versions... if you're using packer-samvera your web server is different from if you're using the "native" dev installation. I'm just not sure how useful it is in helping us make any decisions.

**Comment by hardyoyo** [comment]
I only think we'll look at significant mismatches, hence my column full of questions, which I should call out here. @sgurnick and @mark-dce I have added a column (H) with questions, I call out a few places where version mismatches are apparent, and ask if the mismatch is significant. I also added a column (I) for details, and have used it to list the delegates in use for ImageMagick in dev, in case they are significant

**Comment by mark-dce** [comment]
I think the only reason to worry about FITS, Imagemagick, Graphixmagic, OpenOffice, StarOffice or FFMpeg versions is if you come across content in your holdings that can't be processed by the installed version of one of the tools.  If the version of a tool installed by your package manager works, use that version. 

DCE has at times come across content that couldn't be processed by the then-current package release of a tool like ImageMagick which required us to extract that tool into its own ansible role so we could compile and install a newer version from source.  I'd say we've come across this about 4 times in 5 years working with 30+ institutions, so it's kinda rare.

**Comment by mark-dce** [comment]
@ksclarke Column B is meant to be a reflection of DCE experience and known technical dependencies.  

For instance most of the DCE team develops on OSX, while the majority of our projects deploy to Ubuntu for production; similarly rails integrates puma as the web server for development environments - i.e. unless you've made major configuration changes, running `rails sever` in your development environment is going to launch puma even if you have apache installed on the machine.  Contrastingly, it's technically impossible to develop against Hyrax 2.0 and deploy against Hyrax 2.1.  And while it's technically possible to run different databases in development and production, it's generally discouraged because rails now includes database-dependent configuration in its schema dumps by default (you can override this behavior, but at some loss of functionality)

Column B was meant to be short-hand for these kinds of considerations.  It's meant to be suggestive, not proscriptive and if there are any places UCLA wants to make changes, I don't see any issues.

**Comment by ksclarke** [comment]
Still getting my feet of course, but on our dev instances we won't run `rails server` but use Apache (our dev .env is configured like the prod .env)

**Comment by mark-dce** [comment]
Let's schedule a team review during sprint 3 to gather any additional comments and changes

**Comment by mark-dce** [comment]
Per our team discussion today:
* I copied the relevant UCLA Prod versions over to the UCLA Dev column
* I deleted my initial guesses at UCLA Prod
* I renamed `sgurnick UCLA Prod` to `UCLA Prod` 

With those changes in place, I'm versioning the current document at v1.0 and closing this ticket.  We should, however, treat the spreadsheet as a living document and feel free to update it over time as needed and appropriate.
