### ISSUE TITLE
Document CSV fields and requirements

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#511]
**STORY**
As a librarian preparing a CSV for ingest, I would like documentation of the supported fields, so that I can know I'm creating the file correctly.

**ACCEPTANCE**
- [x] The application provides a link to a static page that describes the structure of a CSV import file
    - [x] Required fields in the file
    - [x] Optional fields in the file
    - [x] Single valued fields
    - [x] Valid values for any controlled fields
    - [x] How to enter multiple values in a field
    - [x] Any other information that helps me construct a CSV for ingest

**EXAMPLES**
https://tenejo.curationexperts.com/importer_documentation/guide
https://samvera.github.io/metadata_application_profile.html

**Comment by val99erie** [comment]
This might be a good starting point:
https://docs.google.com/document/d/14DsXb3EuwexjuTKbelcEUoZwiTqkW1SX-FZ3tjWh-F0

Please make sure that document gets updated with all the correct info.  Or, if we decide that the official CSV documentation should be somewhere other than Google drive, please delete all the stale info out of that document, and add a link to the correct documentation.

**Comment by mark-dce** [comment]
The DCE team discussed this and feels the best place for this information is checked into the repository itself: this doesn't guarantee the documentation will stay in sync with the code, but makes it easier to identify and correct discrepancies than any alternative.

**Comment by bess** [comment]
Prior work example: https://github.com/curationexperts/tenejo/pull/138/files

**Comment by bess** [comment]
![import_a_set_of_records](https://user-images.githubusercontent.com/65608/55647419-9d348600-57ab-11e9-9088-b4228249fb6d.png)
![toc](https://user-images.githubusercontent.com/65608/55647430-a3c2fd80-57ab-11e9-9130-abfd2e3d0408.png)
![required_screenshot](https://user-images.githubusercontent.com/65608/55647435-a7568480-57ab-11e9-9c93-b66309d18c0e.png)

**Comment by bess** [comment]
![required_buttons.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46fa918b368b91ac8bd6bd56b049ff9a3a046b313916ac217586f76ae5002e035c0a1aad45505615fcf0d87ea6b63d228c550cebd0684d68d47f40f2ecdd42e64bef62994597b7bb804dc5ed3921ee8d8b483a1a031c9bb2.png)
