### ISSUE TITLE
Conversation with SUG on search behaviors

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#536]
Meeting among Samvera project team members and SUG. Ideally during SUG regular meeting. This discussion will help in providing information about how the current search configuration works, but more importantly will allow for SUG to share with the Samvera Project leadership team which search attributes are most important or desirable.
Our conversation will cover these topics at a minimum:
- [x] What are the most effective search behaviors (what do users want to do; which users?)
- [x] Default sort

**Approval Criteria**
- [x] A meeting was held with SUG and members of the Samvera Project development team to discuss search, browse, and ranking with some next action steps recorded about how to better align the Californica and Ursus search behaviors to their expectations and/or how to gather more user input.

**Comment by emcaulay** [comment]
@sshaferUCLA  -- This is the ticket about meeting with SUG on April 5 (If Mark and Bess are able to attend) to have a conversation about search-related topics.

**Comment by mark-dce** [comment]
We had a good meeting on Friday 4/5.  Here's the outline of Bess's and my notes:
https://docs.google.com/document/d/1WBBQHR1inumXle7G6NbwXFXc1RKIXUOdwGOvbJiKXFY/edit
