### ISSUE TITLE
Achieve better b-tree distribution in Fedora

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#538]
**ISSUE**
In our current ARK / ID implementation, we are treeify-ing the blade of the ARK - i.e. zz0037f8d becomes treeifyied to /zz/00/37/f8/zz0037f8d

Looking at the UCLA arks, we're concerned that too many begin with the string `zz00...` and we won't get a good binary tree distribution.

**Comment by bess** [comment]
`ModeShape has been designed to efficiently handle a single node having a large number (100K-200k) of child nodes out-of-the-box. However, if an application stores a lot more nodes than that under a single parent, performance in terms of latency and memory consumption starts to decrease proportionally to the number of stored children. `
Source: https://docs.jboss.org/author/display/MODE40/Large+numbers+of+child+nodes#Largenumbersofchildnodes-Unorderedlargecollections

More documentation: 
https://modeshape.wordpress.com/2014/08/14/improving-performance-with-large-numbers-of-child-nodes/

This really does seem relevant to us as I expect we'll quickly outgrow 200k objects at our top level.
