### ISSUE TITLE
Write Tickets for remaining importer fields

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#54]
**ACCEPTANCE**
- [x]  Identify remaining fields required for import of a complete object from the LA Daily News Negatives collection
- [x] Write corresponding tickets to implement each outstanding field

**Comment by mark-dce** [comment]
Mappings are completed and associated tickets are listed in the CSV Mapping tab of this spreadsheet:
https://docs.google.com/spreadsheets/d/1muoNt40y7nKPlthOr_CwuvvXdQLM2uYhEu55GXhASnU/edit#gid=875035976

**Comment by emcaulay** [comment]
I'm assigning myself to review this work.

**Comment by mark-dce** [comment]
Remaining issues to discuss are listed in this agenda:
https://docs.google.com/document/d/1mmwpZhFX1jk1qcHUiZzmEhkFlC0nl838KfBeR_ovils/edit
