### ISSUE TITLE
Allow Lisa to SSH to californica-dev

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/californica#540]
As a project team member, I would like Lisa to be able to use Unix file command to verify that all tiff images are non-corrupt prior to import. 

Use this SSH key please: https://github.com/emcaulay.keys

**Approval Criteria**
- [ ] Lisa can SSH into californica-dev

**Comment by croft103** [comment]
@emcaulay your public key has been added to californica-{dev,test,stage} as the 'deploy' user. You need to go through our bastion host (jump.library.ucla.edu) to connect.

If you have questions or difficulty connecting, let me know.

**Comment by emcaulay** [comment]
@croft103 , I have never used the jump server, so I'm not sure how to use it in relationship to typing this command on my terminal interface: ssh californica-dev

I'm guessing I'll need you or someone to tutor me on this.

**Comment by emcaulay** [comment]
We paired on this today (4/10/19) and Lisa is now up and running.
