### ISSUE TITLE
recreate a pristine californica-stage

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/californica#565]
After changes to our id structure, we need to reingest everything from a blank slate.

Criteria:
- californica-stage is recreated in a pristine state, without any existing data

blocks #528

**Comment by croft103** [comment]
@andrewbenedictwallace the title is for californica-stage, but the ticket references californica-dev. Which environment?

**Comment by andrewbenedictwallace** [comment]
doh! that's stage. updated the description

**Comment by croft103** [comment]
@andrewbenedictwallace californica-stage is in a nascent state and ready for ingest.
