### ISSUE TITLE
Read More/Less with more logic

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/californica#572]
if the total text count is under 600 characters
 no toggle

if the total text count is greater than 600 characters
 toggle at 400 characters

**Comment by mark-dce** [comment]
@jendiamond did you mean for this ticket in californica?  I thought the toggle was just a requirement in ursus.

**Comment by mark-dce** [comment]
making a new ticket in ursus (Jira)

**Comment by mark-dce** [comment]
https://jira.library.ucla.edu/browse/URS-352
