### ISSUE TITLE
A Work has a Genre

### ISSUE THREAD

**Issue by bess** [UCLALibrary/californica#64]
Add a Genre attribute for the `Work` class:

  - [x] A Work object can have a genre field
  - [x] The predicate for it is `edm:hasType`
  - [x] The label for it is "Genre"

**Comment by kjallen** [comment]
We met this morning and discussed the 3rd checkbox, label in this case represents what the field will be called in the Samvera Work class, and is not related to the facet label or other UI components

**Comment by emcaulay** [comment]
The 3rd checkbox is not checked, but this ticket has been closed. Should we remove the 3rd checkbox, or has it been accomplished and it just needs to be checked off?

**Comment by no-reply** [comment]
Per discussion with @bess, the requirement for the label here relates to the attribute name. i.e. this field should be read/writable on `#genre/#genre=`
