### ISSUE TITLE
Confirm Relation.isPartOf metadata handling

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#71]
**ISSUE**
The exported csv metdata [box: dlcs-ladnn-2018-08-10.csv](https://ucla.box.com/s/3z7x6humyhdqpeeq4lwe3xgg5qxx004a) includes the field `Relation.isPartOf`.  

* The field is blank in a very small number of records
* The field contains the following string in over 4000 records
    >Los Angeles Daily News Negatives. Department of Special Collections, Charles E. Young Research Library, University of California at Los Angeles.
* The field contains the following string in 930 records
    >Los Angeles Times Photographic Archive. Department of Special Collections, Charles E. Young Research Library, UCLA.

**ACCEPTANCE**
Chose one of the following options to handle the field:
- [ ] Option 1 - Do not import the field *(easiest & least expensive option)*
- [x] Option 2 - Fill the field with the static string value "Los Angeles Times Photographic Archive. Department of Special Collections, Charles E. Young Research Library, UCLA."
- [ ] Option 3 - Normalize the metadata in the field prior to import into Samvera

**Comment by metaclaudiah** [comment]
Option 2 is best, except that the static string value should be "Los Angeles Daily News Negatives. Department of Special Collections, Charles E. Young Research Library, University of California at Los Angeles."
