### ISSUE TITLE
Implement Base CSV Importer

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#78]
**STORY**
As a repository owner, I would like to be able to import items into California using the exported metadata from the current digital collections site, so that I can minimize manual work that needs to take place to move the collection.

**DETAILS**
A full export of the current collection metadata can be found on [box: dlcs-ladnn-2018-08-10.csv](https://ucla.box.com/s/3z7x6humyhdqpeeq4lwe3xgg5qxx004a).  

For development purposes, we can use the extracted header row and first line in [google docs: LADNN Sample CSV 01.csv](https://drive.google.com/file/d/115r5d-wJaqdjcAI2MmrQL_4-rNJUUFsH/view?usp=sharing)

For the first round, we just need to wire up [Darlingtonia](https://github.com/curationexperts/darlingtonia) to read a CSV file, parse the required fields, and create a new object.  Additional fields will be covered in future tickets.

**ACCEPTANCE** 
- [x] Darlingtonia is added to the application
- [x] Darlingtonia is configured to read a CSV input file like [google docs: LADNN Sample CSV 01.csv](https://drive.google.com/file/d/115r5d-wJaqdjcAI2MmrQL_4-rNJUUFsH/view?usp=sharing)
- [x] The importer reads the `title` field from the CSV file
- [ ] ~The importer sets other required fields to default values~
    - [ ] ~`creator` is set to "Prototype CSV Importer"~
    - [ ] ~`keyword` is set to "pilot data"~
    - [ ] ~`rights` is set to "Copyright Not Evaluated"~
    - [x] **visibility** is set to *Public*
- [x] A new work with the title from the CSV file gets created

**Comment by bess** [comment]
Prior work: https://github.com/curationexperts/mahonia/blob/master/app/importers/mahonia_csv_parser.rb

**Comment by no-reply** [comment]
Can we clarify the need for the `creator`, `keyword`, and `rights` defaults? Will we ever want to ingest data with these values?
