### ISSUE TITLE
ADMIN_PASSWORD is a required environment variable, add to docs and .env.sample

### ISSUE THREAD

**Issue by hardyoyo** [UCLALibrary/californica#89]
As written, the [ADMIN_PASSWORD environment variable is required](https://github.com/UCLALibrary/californica/blob/master/db/seeds.rb#L11). In keeping with recent devops decisions, we should probably just

- [ ] [document the requirement in the developer workspace docs](https://github.com/UCLALibrary/amalgamated-samvera/wiki/Setting-up-a-Californica-development-environment,-"native"-style)
- [ ] update the .env.sample file to include a default password

**Comment by hardyoyo** [comment]
PR #43 added a default admin user and a way to set the password for this user via a .env variable. PR #90 adds a default value for this user, so that initial setup tasks can proceed, even if the ADMIN_PASSWORD variable is not set. We should document this default value, and how it can be set. A simple addition to the README and .env.sample files should be sufficient.

**Comment by no-reply** [comment]
Related to #90

**Comment by hardyoyo** [comment]
PR[#91](https://github.com/UCLALibrary/californica/pull/91) documents this work as described. This is closable.
