### ISSUE TITLE
Change application name (translation) to "Californica"

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/californica#99]
**ISSUE**
The application current displays information something like "Tenejo master; Updated 04 September 2018" in the page footer.

**NOTE**
This is probably a result for the localization file translation entries.

**ACCEPTANCE**
- [ ] The footer lists the application name as "Californica"

**Comment by hardyoyo** [comment]
https://github.com/UCLALibrary/californica/pull/124
